package ee.agri.alkor.model;


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ee.agri.alkor.model.classes.Country;
import ee.agri.alkor.model.classes.ProductType;

/**
 * ReportListView generated by hbm2java
 */
@Entity
@Table(name="report_list_view"
    ,schema="public"
)
public class ReportListView  implements java.io.Serializable {


     private Long aplId;
     private Long aplProductId;
     private String nr;
     private Long id;
     private Date created;
     private Integer amount;
     private String receiver;
     private String partyNr;
     private String marketPlace;
     private String marketAddr;
     private String marketDistr;
     private String marketOrgunit;
     private Long reportId;
     private Long regentryId;
     private String reportingEnt;
     private String reportingEntRegId;
     private String name;
     private ProductType productClassId;
     private Country productOrigCountryClassId;
     private Country producerCountryClassId;
     private String producerName;
     private Date reportDate;

    public ReportListView() {
    }

    public ReportListView(Long aplId, Long aplProductId, String nr, Long id, Date created, Integer amount, String receiver, String partyNr, String marketPlace, String marketAddr, String marketDistr, String marketOrgunit, Long reportId, Long regentryId, Date reportDate, String reportingEnt, String reportingEntRegId, String name, ProductType productClassId, Country productOrigCountryClassId, Country producerCountryClassId) {
       this.aplId = aplId;
       this.aplProductId = aplProductId;
       this.nr = nr;
       this.id = id;
       this.created = created;
       this.amount = amount;
       this.receiver = receiver;
       this.partyNr = partyNr;
       this.marketPlace = marketPlace;
       this.marketAddr = marketAddr;
       this.marketDistr = marketDistr;
       this.marketOrgunit = marketOrgunit;
       this.reportId = reportId;
       this.regentryId = regentryId;
       this.reportingEnt = reportingEnt;
       this.reportingEntRegId = reportingEntRegId;
       this.name = name;
       this.productClassId = productClassId;
       this.productOrigCountryClassId = productOrigCountryClassId;
       this.producerCountryClassId = producerCountryClassId;
       this.reportDate = reportDate;
    }


    @Column(name="apl_id")
    public Long getAplId() {
        return this.aplId;
    }

    public void setAplId(Long aplId) {
        this.aplId = aplId;
    }

    @Column(name="apl_product_id")
    public Long getAplProductId() {
        return this.aplProductId;
    }

    public void setAplProductId(Long aplProductId) {
        this.aplProductId = aplProductId;
    }

    @Column(name="nr", length=20)
    public String getNr() {
        return this.nr;
    }

    public void setNr(String nr) {
        this.nr = nr;
    }
    @Id
    @Column(name="id")
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name="created", length=8)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name="amount")
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name="receiver", length=100)
    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    @Column(name="party_nr", length=20)
    public String getPartyNr() {
        return this.partyNr;
    }

    public void setPartyNr(String partyNr) {
        this.partyNr = partyNr;
    }

    @Column(name="market_place", length=100)
    public String getMarketPlace() {
        return this.marketPlace;
    }

    public void setMarketPlace(String marketPlace) {
        this.marketPlace = marketPlace;
    }

    @Column(name="market_addr", length=64)
    public String getMarketAddr() {
        return this.marketAddr;
    }

    public void setMarketAddr(String marketAddr) {
        this.marketAddr = marketAddr;
    }

    @Column(name="market_distr", length=100)
    public String getMarketDistr() {
        return this.marketDistr;
    }

    public void setMarketDistr(String marketDistr) {
        this.marketDistr = marketDistr;
    }

    @Column(name="market_orgunit", length=100)
    public String getMarketOrgunit() {
        return this.marketOrgunit;
    }

    public void setMarketOrgunit(String marketOrgunit) {
        this.marketOrgunit = marketOrgunit;
    }

    @Column(name="report_id")
    public Long getReportId() {
        return this.reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    @Column(name="regentry_id")
    public Long getRegentryId() {
        return this.regentryId;
    }

    public void setRegentryId(Long regentryId) {
        this.regentryId = regentryId;
    }
    
    @Column(name="report_date")
    public Date getReportDate()
    {
    	return this.reportDate;
    }
    
    public void setReportDate(Date reportDate)
    {
    	this.reportDate = reportDate;
    }

    @Column(name="reporting_ent", length=128)
    public String getReportingEnt() {
        return this.reportingEnt;
    }

    public void setReportingEnt(String reportingEnt) {
        this.reportingEnt = reportingEnt;
    }

    @Column(name="reporting_ent_reg_id", length=40)
    public String getReportingEntRegId() {
        return this.reportingEntRegId;
    }

    public void setReportingEntRegId(String reportingEntRegId) {
        this.reportingEntRegId = reportingEntRegId;
    }

    @Column(name="name", length=256)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToOne (cascade = CascadeType.REFRESH)
    @JoinColumn(name="product_class_id")
    public ProductType getProductClassId() {
        return this.productClassId;
    }

    public void setProductClassId(ProductType productClassId) {
        this.productClassId = productClassId;
    }

    @ManyToOne (cascade = CascadeType.REFRESH)
    @JoinColumn(name="product_orig_country_class_id")
    public Country getProductOrigCountryClassId() {
        return this.productOrigCountryClassId;
    }

    public void setProductOrigCountryClassId(Country productOrigCountryClassId) {
        this.productOrigCountryClassId = productOrigCountryClassId;
    }
    
    @Column(name="producer_name")
    public String getProducerName() {
		return producerName;
	}
    
    public void setProducerName(String producerName) {
		this.producerName = producerName;
	}

    @ManyToOne (cascade = CascadeType.REFRESH)
    @JoinColumn(name="producer_country_class_id")
    public Country getProducerCountryClassId() {
        return this.producerCountryClassId;
    }

    public void setProducerCountryClassId(Country producerCountryClassId) {
        this.producerCountryClassId = producerCountryClassId;
    }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAplId() == null ? 0 : this.getAplId().hashCode() );
         result = 37 * result + ( getAplProductId() == null ? 0 : this.getAplProductId().hashCode() );
         result = 37 * result + ( getNr() == null ? 0 : this.getNr().hashCode() );
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         result = 37 * result + ( getAmount() == null ? 0 : this.getAmount().hashCode() );
         result = 37 * result + ( getReceiver() == null ? 0 : this.getReceiver().hashCode() );
         result = 37 * result + ( getPartyNr() == null ? 0 : this.getPartyNr().hashCode() );
         result = 37 * result + ( getMarketPlace() == null ? 0 : this.getMarketPlace().hashCode() );
         result = 37 * result + ( getMarketAddr() == null ? 0 : this.getMarketAddr().hashCode() );
         result = 37 * result + ( getMarketDistr() == null ? 0 : this.getMarketDistr().hashCode() );
         result = 37 * result + ( getMarketOrgunit() == null ? 0 : this.getMarketOrgunit().hashCode() );
         result = 37 * result + ( getReportId() == null ? 0 : this.getReportId().hashCode() );
         result = 37 * result + ( getRegentryId() == null ? 0 : this.getRegentryId().hashCode() );
         result = 37 * result + ( getReportingEnt() == null ? 0 : this.getReportingEnt().hashCode() );
         result = 37 * result + ( getReportingEntRegId() == null ? 0 : this.getReportingEntRegId().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getProductClassId() == null ? 0 : this.getProductClassId().hashCode() );
         result = 37 * result + ( getProductOrigCountryClassId() == null ? 0 : this.getProductOrigCountryClassId().hashCode() );
         result = 37 * result + ( getProducerCountryClassId() == null ? 0 : this.getProducerCountryClassId().hashCode() );
         result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
         return result;
   }


}


