/**
 * CountryType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package eu.x_road.alkor2;

public class CountryType implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected CountryType(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _AF = "AF";
    public static final java.lang.String _AL = "AL";
    public static final java.lang.String _DZ = "DZ";
    public static final java.lang.String _AS = "AS";
    public static final java.lang.String _US = "US";
    public static final java.lang.String _AD = "AD";
    public static final java.lang.String _AO = "AO";
    public static final java.lang.String _AI = "AI";
    public static final java.lang.String _AQ = "AQ";
    public static final java.lang.String _AG = "AG";
    public static final java.lang.String _AE = "AE";
    public static final java.lang.String _AR = "AR";
    public static final java.lang.String _AM = "AM";
    public static final java.lang.String _AW = "AW";
    public static final java.lang.String _AZ = "AZ";
    public static final java.lang.String _AU = "AU";
    public static final java.lang.String _AT = "AT";
    public static final java.lang.String _BS = "BS";
    public static final java.lang.String _BH = "BH";
    public static final java.lang.String _BD = "BD";
    public static final java.lang.String _BB = "BB";
    public static final java.lang.String _PW = "PW";
    public static final java.lang.String _BE = "BE";
    public static final java.lang.String _BZ = "BZ";
    public static final java.lang.String _BJ = "BJ";
    public static final java.lang.String _BM = "BM";
    public static final java.lang.String _BT = "BT";
    public static final java.lang.String _BOL = "BOL";
    public static final java.lang.String _BQ = "BQ";
    public static final java.lang.String _BA = "BA";
    public static final java.lang.String _BW = "BW";
    public static final java.lang.String _BV = "BV";
    public static final java.lang.String _BR = "BR";
    public static final java.lang.String _IO = "IO";
    public static final java.lang.String _VG = "VG";
    public static final java.lang.String _BN = "BN";
    public static final java.lang.String _BG = "BG";
    public static final java.lang.String _BF = "BF";
    public static final java.lang.String _BI = "BI";
    public static final java.lang.String _CO = "CO";
    public static final java.lang.String _CK = "CK";
    public static final java.lang.String _CR = "CR";
    public static final java.lang.String _CW = "CW";
    public static final java.lang.String _DJ = "DJ";
    public static final java.lang.String _DM = "DM";
    public static final java.lang.String _DO = "DO";
    public static final java.lang.String _EC = "EC";
    public static final java.lang.String _EE = "EE";
    public static final java.lang.String _EG = "EG";
    public static final java.lang.String _GQ = "GQ";
    public static final java.lang.String _CI = "CI";
    public static final java.lang.String _SV = "SV";
    public static final java.lang.String _ER = "ER";
    public static final java.lang.String _ET = "ET";
    public static final java.lang.String _EU = "EU";
    public static final java.lang.String _FO = "FO";
    public static final java.lang.String _FK = "FK";
    public static final java.lang.String _FJ = "FJ";
    public static final java.lang.String _PH = "PH";
    public static final java.lang.String _GA = "GA";
    public static final java.lang.String _GM = "GM";
    public static final java.lang.String _GH = "GH";
    public static final java.lang.String _GI = "GI";
    public static final java.lang.String _GD = "GD";
    public static final java.lang.String _GL = "GL";
    public static final java.lang.String _GE = "GE";
    public static final java.lang.String _GP = "GP";
    public static final java.lang.String _GU = "GU";
    public static final java.lang.String _GT = "GT";
    public static final java.lang.String _GG = "GG";
    public static final java.lang.String _GN = "GN";
    public static final java.lang.String _GW = "GW";
    public static final java.lang.String _GY = "GY";
    public static final java.lang.String _HT = "HT";
    public static final java.lang.String _HM = "HM";
    public static final java.lang.String _CN = "CN";
    public static final java.lang.String _ES = "ES";
    public static final java.lang.String _NL = "NL";
    public static final java.lang.String _AN = "AN";
    public static final java.lang.String _HN = "HN";
    public static final java.lang.String _HK = "HK";
    public static final java.lang.String _HR = "HR";
    public static final java.lang.String _IE = "IE";
    public static final java.lang.String _IL = "IL";
    public static final java.lang.String _IN = "IN";
    public static final java.lang.String _ID = "ID";
    public static final java.lang.String _IQ = "IQ";
    public static final java.lang.String _IR = "IR";
    public static final java.lang.String _IS = "IS";
    public static final java.lang.String _IT = "IT";
    public static final java.lang.String _JP = "JP";
    public static final java.lang.String _JM = "JM";
    public static final java.lang.String _YE = "YE";
    public static final java.lang.String _JE = "JE";
    public static final java.lang.String _JO = "JO";
    public static final java.lang.String _CX = "CX";
    public static final java.lang.String _KY = "KY";
    public static final java.lang.String _KH = "KH";
    public static final java.lang.String _CM = "CM";
    public static final java.lang.String _CA = "CA";
    public static final java.lang.String _CBI = "CBI";
    public static final java.lang.String _KZ = "KZ";
    public static final java.lang.String _QA = "QA";
    public static final java.lang.String _KE = "KE";
    public static final java.lang.String _CF = "CF";
    public static final java.lang.String _KI = "KI";
    public static final java.lang.String _KM = "KM";
    public static final java.lang.String _CD = "CD";
    public static final java.lang.String _CG = "CG";
    public static final java.lang.String _CC = "CC";
    public static final java.lang.String _KP = "KP";
    public static final java.lang.String _KR = "KR";
    public static final java.lang.String _KG = "KG";
    public static final java.lang.String _XK = "XK";
    public static final java.lang.String _GR = "GR";
    public static final java.lang.String _CY = "CY";
    public static final java.lang.String _CU = "CU";
    public static final java.lang.String _KW = "KW";
    public static final java.lang.String _WI = "WI";
    public static final java.lang.String _EH = "EH";
    public static final java.lang.String _LA = "LA";
    public static final java.lang.String _LV = "LV";
    public static final java.lang.String _LT = "LT";
    public static final java.lang.String _LS = "LS";
    public static final java.lang.String _LR = "LR";
    public static final java.lang.String _LI = "LI";
    public static final java.lang.String _LB = "LB";
    public static final java.lang.String _LY = "LY";
    public static final java.lang.String _ZA = "ZA";
    public static final java.lang.String _GS = "GS";
    public static final java.lang.String _SS = "SS";
    public static final java.lang.String _LU = "LU";
    public static final java.lang.String _MO = "MO";
    public static final java.lang.String _MG = "MG";
    public static final java.lang.String _MK = "MK";
    public static final java.lang.String _MY = "MY";
    public static final java.lang.String _MW = "MW";
    public static final java.lang.String _MV = "MV";
    public static final java.lang.String _ML = "ML";
    public static final java.lang.String _MT = "MT";
    public static final java.lang.String _IM = "IM";
    public static final java.lang.String _MA = "MA";
    public static final java.lang.String _MH = "MH";
    public static final java.lang.String _MQ = "MQ";
    public static final java.lang.String _MR = "MR";
    public static final java.lang.String _MU = "MU";
    public static final java.lang.String _YT = "YT";
    public static final java.lang.String _MX = "MX";
    public static final java.lang.String _FM = "FM";
    public static final java.lang.String _MD = "MD";
    public static final java.lang.String _MC = "MC";
    public static final java.lang.String _MN = "MN";
    public static final java.lang.String _ME = "ME";
    public static final java.lang.String _MS = "MS";
    public static final java.lang.String _MZ = "MZ";
    public static final java.lang.String _MM = "MM";
    public static final java.lang.String _NA = "NA";
    public static final java.lang.String _NR = "NR";
    public static final java.lang.String _NP = "NP";
    public static final java.lang.String _NI = "NI";
    public static final java.lang.String _NG = "NG";
    public static final java.lang.String _NE = "NE";
    public static final java.lang.String _NU = "NU";
    public static final java.lang.String _KK = "KK";
    public static final java.lang.String _NF = "NF";
    public static final java.lang.String _NO = "NO";
    public static final java.lang.String _OM = "OM";
    public static final java.lang.String _PG = "PG";
    public static final java.lang.String _PK = "PK";
    public static final java.lang.String _PA = "PA";
    public static final java.lang.String _PY = "PY";
    public static final java.lang.String _PE = "PE";
    public static final java.lang.String _PN = "PN";
    public static final java.lang.String _MP = "MP";
    public static final java.lang.String _PL = "PL";
    public static final java.lang.String _PT = "PT";
    public static final java.lang.String _FR = "FR";
    public static final java.lang.String _PR = "PR";
    public static final java.lang.String _VA = "VA";
    public static final java.lang.String _RE = "RE";
    public static final java.lang.String _CV = "CV";
    public static final java.lang.String _SE = "SE";
    public static final java.lang.String _RO = "RO";
    public static final java.lang.String _RW = "RW";
    public static final java.lang.String _SB = "SB";
    public static final java.lang.String _BL = "BL";
    public static final java.lang.String _SH = "SH";
    public static final java.lang.String _KN = "KN";
    public static final java.lang.String _LC = "LC";
    public static final java.lang.String _MF = "MF";
    public static final java.lang.String _PM = "PM";
    public static final java.lang.String _VC = "VC";
    public static final java.lang.String _DE = "DE";
    public static final java.lang.String _ZM = "ZM";
    public static final java.lang.String _WS = "WS";
    public static final java.lang.String _SM = "SM";
    public static final java.lang.String _ST = "ST";
    public static final java.lang.String _SA = "SA";
    public static final java.lang.String _SC = "SC";
    public static final java.lang.String _SN = "SN";
    public static final java.lang.String _XS = "XS";
    public static final java.lang.String _SL = "SL";
    public static final java.lang.String _SG = "SG";
    public static final java.lang.String _SX = "SX";
    public static final java.lang.String _SK = "SK";
    public static final java.lang.String _SI = "SI";
    public static final java.lang.String _SO = "SO";
    public static final java.lang.String _FI = "FI";
    public static final java.lang.String _SCO = "SCO";
    public static final java.lang.String _LK = "LK";
    public static final java.lang.String _SD = "SD";
    public static final java.lang.String _SR = "SR";
    public static final java.lang.String _GB = "GB";
    public static final java.lang.String _SY = "SY";
    public static final java.lang.String _SZ = "SZ";
    public static final java.lang.String _SJ = "SJ";
    public static final java.lang.String _CH = "CH";
    public static final java.lang.String _DK = "DK";
    public static final java.lang.String _TJ = "TJ";
    public static final java.lang.String _TH = "TH";
    public static final java.lang.String _TW = "TW";
    public static final java.lang.String _TZ = "TZ";
    public static final java.lang.String _TL = "TL";
    public static final java.lang.String _TG = "TG";
    public static final java.lang.String _TK = "TK";
    public static final java.lang.String _TO = "TO";
    public static final java.lang.String _TT = "TT";
    public static final java.lang.String _TD = "TD";
    public static final java.lang.String _CZ = "CZ";
    public static final java.lang.String _CL = "CL";
    public static final java.lang.String _TN = "TN";
    public static final java.lang.String _TR = "TR";
    public static final java.lang.String _TM = "TM";
    public static final java.lang.String _TC = "TC";
    public static final java.lang.String _TV = "TV";
    public static final java.lang.String _UG = "UG";
    public static final java.lang.String _UM = "UM";
    public static final java.lang.String _UA = "UA";
    public static final java.lang.String _HU = "HU";
    public static final java.lang.String _XX = "XX";
    public static final java.lang.String _UY = "UY";
    public static final java.lang.String _VI = "VI";
    public static final java.lang.String _UZ = "UZ";
    public static final java.lang.String _NC = "NC";
    public static final java.lang.String _NZ = "NZ";
    public static final java.lang.String _BY = "BY";
    public static final java.lang.String _VU = "VU";
    public static final java.lang.String _RU = "RU";
    public static final java.lang.String _VE = "VE";
    public static final java.lang.String _VN = "VN";
    public static final java.lang.String _WF = "WF";
    public static final java.lang.String _ZW = "ZW";
    public static final CountryType AF = new CountryType(_AF);
    public static final CountryType AL = new CountryType(_AL);
    public static final CountryType DZ = new CountryType(_DZ);
    public static final CountryType AS = new CountryType(_AS);
    public static final CountryType US = new CountryType(_US);
    public static final CountryType AD = new CountryType(_AD);
    public static final CountryType AO = new CountryType(_AO);
    public static final CountryType AI = new CountryType(_AI);
    public static final CountryType AQ = new CountryType(_AQ);
    public static final CountryType AG = new CountryType(_AG);
    public static final CountryType AE = new CountryType(_AE);
    public static final CountryType AR = new CountryType(_AR);
    public static final CountryType AM = new CountryType(_AM);
    public static final CountryType AW = new CountryType(_AW);
    public static final CountryType AZ = new CountryType(_AZ);
    public static final CountryType AU = new CountryType(_AU);
    public static final CountryType AT = new CountryType(_AT);
    public static final CountryType BS = new CountryType(_BS);
    public static final CountryType BH = new CountryType(_BH);
    public static final CountryType BD = new CountryType(_BD);
    public static final CountryType BB = new CountryType(_BB);
    public static final CountryType PW = new CountryType(_PW);
    public static final CountryType BE = new CountryType(_BE);
    public static final CountryType BZ = new CountryType(_BZ);
    public static final CountryType BJ = new CountryType(_BJ);
    public static final CountryType BM = new CountryType(_BM);
    public static final CountryType BT = new CountryType(_BT);
    public static final CountryType BOL = new CountryType(_BOL);
    public static final CountryType BQ = new CountryType(_BQ);
    public static final CountryType BA = new CountryType(_BA);
    public static final CountryType BW = new CountryType(_BW);
    public static final CountryType BV = new CountryType(_BV);
    public static final CountryType BR = new CountryType(_BR);
    public static final CountryType IO = new CountryType(_IO);
    public static final CountryType VG = new CountryType(_VG);
    public static final CountryType BN = new CountryType(_BN);
    public static final CountryType BG = new CountryType(_BG);
    public static final CountryType BF = new CountryType(_BF);
    public static final CountryType BI = new CountryType(_BI);
    public static final CountryType CO = new CountryType(_CO);
    public static final CountryType CK = new CountryType(_CK);
    public static final CountryType CR = new CountryType(_CR);
    public static final CountryType CW = new CountryType(_CW);
    public static final CountryType DJ = new CountryType(_DJ);
    public static final CountryType DM = new CountryType(_DM);
    public static final CountryType DO = new CountryType(_DO);
    public static final CountryType EC = new CountryType(_EC);
    public static final CountryType EE = new CountryType(_EE);
    public static final CountryType EG = new CountryType(_EG);
    public static final CountryType GQ = new CountryType(_GQ);
    public static final CountryType CI = new CountryType(_CI);
    public static final CountryType SV = new CountryType(_SV);
    public static final CountryType ER = new CountryType(_ER);
    public static final CountryType ET = new CountryType(_ET);
    public static final CountryType EU = new CountryType(_EU);
    public static final CountryType FO = new CountryType(_FO);
    public static final CountryType FK = new CountryType(_FK);
    public static final CountryType FJ = new CountryType(_FJ);
    public static final CountryType PH = new CountryType(_PH);
    public static final CountryType GA = new CountryType(_GA);
    public static final CountryType GM = new CountryType(_GM);
    public static final CountryType GH = new CountryType(_GH);
    public static final CountryType GI = new CountryType(_GI);
    public static final CountryType GD = new CountryType(_GD);
    public static final CountryType GL = new CountryType(_GL);
    public static final CountryType GE = new CountryType(_GE);
    public static final CountryType GP = new CountryType(_GP);
    public static final CountryType GU = new CountryType(_GU);
    public static final CountryType GT = new CountryType(_GT);
    public static final CountryType GG = new CountryType(_GG);
    public static final CountryType GN = new CountryType(_GN);
    public static final CountryType GW = new CountryType(_GW);
    public static final CountryType GY = new CountryType(_GY);
    public static final CountryType HT = new CountryType(_HT);
    public static final CountryType HM = new CountryType(_HM);
    public static final CountryType CN = new CountryType(_CN);
    public static final CountryType ES = new CountryType(_ES);
    public static final CountryType NL = new CountryType(_NL);
    public static final CountryType AN = new CountryType(_AN);
    public static final CountryType HN = new CountryType(_HN);
    public static final CountryType HK = new CountryType(_HK);
    public static final CountryType HR = new CountryType(_HR);
    public static final CountryType IE = new CountryType(_IE);
    public static final CountryType IL = new CountryType(_IL);
    public static final CountryType IN = new CountryType(_IN);
    public static final CountryType ID = new CountryType(_ID);
    public static final CountryType IQ = new CountryType(_IQ);
    public static final CountryType IR = new CountryType(_IR);
    public static final CountryType IS = new CountryType(_IS);
    public static final CountryType IT = new CountryType(_IT);
    public static final CountryType JP = new CountryType(_JP);
    public static final CountryType JM = new CountryType(_JM);
    public static final CountryType YE = new CountryType(_YE);
    public static final CountryType JE = new CountryType(_JE);
    public static final CountryType JO = new CountryType(_JO);
    public static final CountryType CX = new CountryType(_CX);
    public static final CountryType KY = new CountryType(_KY);
    public static final CountryType KH = new CountryType(_KH);
    public static final CountryType CM = new CountryType(_CM);
    public static final CountryType CA = new CountryType(_CA);
    public static final CountryType CBI = new CountryType(_CBI);
    public static final CountryType KZ = new CountryType(_KZ);
    public static final CountryType QA = new CountryType(_QA);
    public static final CountryType KE = new CountryType(_KE);
    public static final CountryType CF = new CountryType(_CF);
    public static final CountryType KI = new CountryType(_KI);
    public static final CountryType KM = new CountryType(_KM);
    public static final CountryType CD = new CountryType(_CD);
    public static final CountryType CG = new CountryType(_CG);
    public static final CountryType CC = new CountryType(_CC);
    public static final CountryType KP = new CountryType(_KP);
    public static final CountryType KR = new CountryType(_KR);
    public static final CountryType KG = new CountryType(_KG);
    public static final CountryType XK = new CountryType(_XK);
    public static final CountryType GR = new CountryType(_GR);
    public static final CountryType CY = new CountryType(_CY);
    public static final CountryType CU = new CountryType(_CU);
    public static final CountryType KW = new CountryType(_KW);
    public static final CountryType WI = new CountryType(_WI);
    public static final CountryType EH = new CountryType(_EH);
    public static final CountryType LA = new CountryType(_LA);
    public static final CountryType LV = new CountryType(_LV);
    public static final CountryType LT = new CountryType(_LT);
    public static final CountryType LS = new CountryType(_LS);
    public static final CountryType LR = new CountryType(_LR);
    public static final CountryType LI = new CountryType(_LI);
    public static final CountryType LB = new CountryType(_LB);
    public static final CountryType LY = new CountryType(_LY);
    public static final CountryType ZA = new CountryType(_ZA);
    public static final CountryType GS = new CountryType(_GS);
    public static final CountryType SS = new CountryType(_SS);
    public static final CountryType LU = new CountryType(_LU);
    public static final CountryType MO = new CountryType(_MO);
    public static final CountryType MG = new CountryType(_MG);
    public static final CountryType MK = new CountryType(_MK);
    public static final CountryType MY = new CountryType(_MY);
    public static final CountryType MW = new CountryType(_MW);
    public static final CountryType MV = new CountryType(_MV);
    public static final CountryType ML = new CountryType(_ML);
    public static final CountryType MT = new CountryType(_MT);
    public static final CountryType IM = new CountryType(_IM);
    public static final CountryType MA = new CountryType(_MA);
    public static final CountryType MH = new CountryType(_MH);
    public static final CountryType MQ = new CountryType(_MQ);
    public static final CountryType MR = new CountryType(_MR);
    public static final CountryType MU = new CountryType(_MU);
    public static final CountryType YT = new CountryType(_YT);
    public static final CountryType MX = new CountryType(_MX);
    public static final CountryType FM = new CountryType(_FM);
    public static final CountryType MD = new CountryType(_MD);
    public static final CountryType MC = new CountryType(_MC);
    public static final CountryType MN = new CountryType(_MN);
    public static final CountryType ME = new CountryType(_ME);
    public static final CountryType MS = new CountryType(_MS);
    public static final CountryType MZ = new CountryType(_MZ);
    public static final CountryType MM = new CountryType(_MM);
    public static final CountryType NA = new CountryType(_NA);
    public static final CountryType NR = new CountryType(_NR);
    public static final CountryType NP = new CountryType(_NP);
    public static final CountryType NI = new CountryType(_NI);
    public static final CountryType NG = new CountryType(_NG);
    public static final CountryType NE = new CountryType(_NE);
    public static final CountryType NU = new CountryType(_NU);
    public static final CountryType KK = new CountryType(_KK);
    public static final CountryType NF = new CountryType(_NF);
    public static final CountryType NO = new CountryType(_NO);
    public static final CountryType OM = new CountryType(_OM);
    public static final CountryType PG = new CountryType(_PG);
    public static final CountryType PK = new CountryType(_PK);
    public static final CountryType PA = new CountryType(_PA);
    public static final CountryType PY = new CountryType(_PY);
    public static final CountryType PE = new CountryType(_PE);
    public static final CountryType PN = new CountryType(_PN);
    public static final CountryType MP = new CountryType(_MP);
    public static final CountryType PL = new CountryType(_PL);
    public static final CountryType PT = new CountryType(_PT);
    public static final CountryType FR = new CountryType(_FR);
    public static final CountryType PR = new CountryType(_PR);
    public static final CountryType VA = new CountryType(_VA);
    public static final CountryType RE = new CountryType(_RE);
    public static final CountryType CV = new CountryType(_CV);
    public static final CountryType SE = new CountryType(_SE);
    public static final CountryType RO = new CountryType(_RO);
    public static final CountryType RW = new CountryType(_RW);
    public static final CountryType SB = new CountryType(_SB);
    public static final CountryType BL = new CountryType(_BL);
    public static final CountryType SH = new CountryType(_SH);
    public static final CountryType KN = new CountryType(_KN);
    public static final CountryType LC = new CountryType(_LC);
    public static final CountryType MF = new CountryType(_MF);
    public static final CountryType PM = new CountryType(_PM);
    public static final CountryType VC = new CountryType(_VC);
    public static final CountryType DE = new CountryType(_DE);
    public static final CountryType ZM = new CountryType(_ZM);
    public static final CountryType WS = new CountryType(_WS);
    public static final CountryType SM = new CountryType(_SM);
    public static final CountryType ST = new CountryType(_ST);
    public static final CountryType SA = new CountryType(_SA);
    public static final CountryType SC = new CountryType(_SC);
    public static final CountryType SN = new CountryType(_SN);
    public static final CountryType XS = new CountryType(_XS);
    public static final CountryType SL = new CountryType(_SL);
    public static final CountryType SG = new CountryType(_SG);
    public static final CountryType SX = new CountryType(_SX);
    public static final CountryType SK = new CountryType(_SK);
    public static final CountryType SI = new CountryType(_SI);
    public static final CountryType SO = new CountryType(_SO);
    public static final CountryType FI = new CountryType(_FI);
    public static final CountryType SCO = new CountryType(_SCO);
    public static final CountryType LK = new CountryType(_LK);
    public static final CountryType SD = new CountryType(_SD);
    public static final CountryType SR = new CountryType(_SR);
    public static final CountryType GB = new CountryType(_GB);
    public static final CountryType SY = new CountryType(_SY);
    public static final CountryType SZ = new CountryType(_SZ);
    public static final CountryType SJ = new CountryType(_SJ);
    public static final CountryType CH = new CountryType(_CH);
    public static final CountryType DK = new CountryType(_DK);
    public static final CountryType TJ = new CountryType(_TJ);
    public static final CountryType TH = new CountryType(_TH);
    public static final CountryType TW = new CountryType(_TW);
    public static final CountryType TZ = new CountryType(_TZ);
    public static final CountryType TL = new CountryType(_TL);
    public static final CountryType TG = new CountryType(_TG);
    public static final CountryType TK = new CountryType(_TK);
    public static final CountryType TO = new CountryType(_TO);
    public static final CountryType TT = new CountryType(_TT);
    public static final CountryType TD = new CountryType(_TD);
    public static final CountryType CZ = new CountryType(_CZ);
    public static final CountryType CL = new CountryType(_CL);
    public static final CountryType TN = new CountryType(_TN);
    public static final CountryType TR = new CountryType(_TR);
    public static final CountryType TM = new CountryType(_TM);
    public static final CountryType TC = new CountryType(_TC);
    public static final CountryType TV = new CountryType(_TV);
    public static final CountryType UG = new CountryType(_UG);
    public static final CountryType UM = new CountryType(_UM);
    public static final CountryType UA = new CountryType(_UA);
    public static final CountryType HU = new CountryType(_HU);
    public static final CountryType XX = new CountryType(_XX);
    public static final CountryType UY = new CountryType(_UY);
    public static final CountryType VI = new CountryType(_VI);
    public static final CountryType UZ = new CountryType(_UZ);
    public static final CountryType NC = new CountryType(_NC);
    public static final CountryType NZ = new CountryType(_NZ);
    public static final CountryType BY = new CountryType(_BY);
    public static final CountryType VU = new CountryType(_VU);
    public static final CountryType RU = new CountryType(_RU);
    public static final CountryType VE = new CountryType(_VE);
    public static final CountryType VN = new CountryType(_VN);
    public static final CountryType WF = new CountryType(_WF);
    public static final CountryType ZW = new CountryType(_ZW);
    public java.lang.String getValue() { return _value_;}
    public static CountryType fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        CountryType enumeration = (CountryType)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static CountryType fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(CountryType.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://alkor2.x-road.eu/", "CountryType"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
