package ee.agri.alkor.util.convert.model.pmr;

// Generated 21.02.2007 13:08:27 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AtEnt generated by hbm2java
 */
@Entity
@Table(name = "at_ent", catalog = "alkoreg")
public class AtEnt implements java.io.Serializable {

	private String regNr;

	private String name;

	private String tel;

	private String fax;

	private String email;

	private String address;

	private int permitted;

	public AtEnt() {
	}

	public AtEnt(String regNr, int permitted) {
		this.regNr = regNr;
		this.permitted = permitted;
	}

	public AtEnt(String regNr, String name, String tel, String fax,
			String email, String address, int permitted) {
		this.regNr = regNr;
		this.name = name;
		this.tel = tel;
		this.fax = fax;
		this.email = email;
		this.address = address;
		this.permitted = permitted;
	}

	@Id
	@Column(name = "reg_nr", unique = true, nullable = false, length = 10)
	public String getRegNr() {
		return this.regNr;
	}

	public void setRegNr(String regNr) {
		this.regNr = regNr;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "permitted", nullable = false)
	public int getPermitted() {
		return this.permitted;
	}

	public void setPermitted(int permitted) {
		this.permitted = permitted;
	}

}
