package ee.agri.alkor.util.convert.model.pmr;

// Generated 21.02.2007 13:08:27 by Hibernate Tools 3.2.0.b9

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AtReportRcd generated by hbm2java
 */
@Entity
@Table(name = "at_report_rcd", catalog = "alkoreg")
public class AtReportRcd implements java.io.Serializable {

	private int id;

	private AtReport report;

	private int status;

	private String regBookNr;

	private String receiver;

	private String market;

	private String addrCounty;

	private String addrTown;

	private String addrStr;

	private String PNr;

	private int PCnt;

	public AtReportRcd() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne (cascade = CascadeType.REFRESH)
	@JoinColumn(name="report_id")
	public AtReport getReport() {
		return this.report;
	}

	public void setReport(AtReport report) {
		this.report = report;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "reg_book_nr", nullable = false, length = 25)
	public String getRegBookNr() {
		return this.regBookNr;
	}

	public void setRegBookNr(String regBookNr) {
		this.regBookNr = regBookNr;
	}

	@Column(name = "receiver", nullable = false, length = 100)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "market", nullable = false, length = 100)
	public String getMarket() {
		return this.market;
	}

	public void setMarket(String market) {
		this.market = market;
	}

	@Column(name = "addr_county", nullable = false, length = 20)
	public String getAddrCounty() {
		return this.addrCounty;
	}

	public void setAddrCounty(String addrCounty) {
		this.addrCounty = addrCounty;
	}

	@Column(name = "addr_town", nullable = false, length = 30)
	public String getAddrTown() {
		return this.addrTown;
	}

	public void setAddrTown(String addrTown) {
		this.addrTown = addrTown;
	}

	@Column(name = "addr_str", nullable = false, length = 30)
	public String getAddrStr() {
		return this.addrStr;
	}

	public void setAddrStr(String addrStr) {
		this.addrStr = addrStr;
	}

	@Column(name = "p_nr", nullable = false, length = 20)
	public String getPNr() {
		return this.PNr;
	}

	public void setPNr(String PNr) {
		this.PNr = PNr;
	}

	@Column(name = "p_cnt", nullable = false)
	public int getPCnt() {
		return this.PCnt;
	}

	public void setPCnt(int PCnt) {
		this.PCnt = PCnt;
	}

}
