package ee.agri.alkor.util.convert.model.pmr;

// Generated 21.02.2007 13:08:27 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AtReport generated by hbm2java
 */
@Entity
@Table(name = "at_report", catalog = "alkoreg")
public class AtReport implements java.io.Serializable {

	private int id;

	private Date loadDate;

	private String loadRegNr;

	private String loadUser;

	private int source;

	private String entRegNr;

	private String entName;

	private String entTel;

	private String entFax;

	private String entEmail;

	private String entAddress;

	private Integer repYear;

	private Integer repMonth;
	
	private Set records = new HashSet();

	public AtReport() {
	}

	public AtReport(int id, Date loadDate, String loadRegNr, int source,
			String entRegNr) {
		this.id = id;
		this.loadDate = loadDate;
		this.loadRegNr = loadRegNr;
		this.source = source;
		this.entRegNr = entRegNr;
	}

	public AtReport(int id, Date loadDate, String loadRegNr, String loadUser,
			int source, String entRegNr, String entName, String entTel,
			String entFax, String entEmail, String entAddress, Integer repYear,
			Integer repMonth) {
		this.id = id;
		this.loadDate = loadDate;
		this.loadRegNr = loadRegNr;
		this.loadUser = loadUser;
		this.source = source;
		this.entRegNr = entRegNr;
		this.entName = entName;
		this.entTel = entTel;
		this.entFax = entFax;
		this.entEmail = entEmail;
		this.entAddress = entAddress;
		this.repYear = repYear;
		this.repMonth = repMonth;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "load_date", nullable = false, length = 10)
	public Date getLoadDate() {
		return this.loadDate;
	}

	public void setLoadDate(Date loadDate) {
		this.loadDate = loadDate;
	}

	@Column(name = "load_reg_nr", nullable = false, length = 10)
	public String getLoadRegNr() {
		return this.loadRegNr;
	}

	public void setLoadRegNr(String loadRegNr) {
		this.loadRegNr = loadRegNr;
	}

	@Column(name = "load_user", length = 15)
	public String getLoadUser() {
		return this.loadUser;
	}

	public void setLoadUser(String loadUser) {
		this.loadUser = loadUser;
	}

	@Column(name = "source", nullable = false)
	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	@Column(name = "ent_reg_nr", nullable = false, length = 10)
	public String getEntRegNr() {
		return this.entRegNr;
	}

	public void setEntRegNr(String entRegNr) {
		this.entRegNr = entRegNr;
	}

	@Column(name = "ent_name", length = 100)
	public String getEntName() {
		return this.entName;
	}

	public void setEntName(String entName) {
		this.entName = entName;
	}

	@Column(name = "ent_tel", length = 20)
	public String getEntTel() {
		return this.entTel;
	}

	public void setEntTel(String entTel) {
		this.entTel = entTel;
	}

	@Column(name = "ent_fax", length = 20)
	public String getEntFax() {
		return this.entFax;
	}

	public void setEntFax(String entFax) {
		this.entFax = entFax;
	}

	@Column(name = "ent_email", length = 50)
	public String getEntEmail() {
		return this.entEmail;
	}

	public void setEntEmail(String entEmail) {
		this.entEmail = entEmail;
	}

	@Column(name = "ent_address", length = 100)
	public String getEntAddress() {
		return this.entAddress;
	}

	public void setEntAddress(String entAddress) {
		this.entAddress = entAddress;
	}

	@Column(name = "rep_year")
	public Integer getRepYear() {
		return this.repYear;
	}

	public void setRepYear(Integer repYear) {
		this.repYear = repYear;
	}

	@Column(name = "rep_month")
	public Integer getRepMonth() {
		return this.repMonth;
	}

	public void setRepMonth(Integer repMonth) {
		this.repMonth = repMonth;
	}

	@OneToMany(cascade = CascadeType.REFRESH, fetch = FetchType.EAGER, mappedBy = "report")
	public Set<AtReportRcd> getRecords() {
		return records;
	}

	public void setRecords(Set records) {
		this.records = records;
	}

}
