package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArAaRelId generated by hbm2java
 */
@Embeddable
public class ArAaRelId implements java.io.Serializable {

	private int actor1Id;

	private int actor2Id;

	private short type;

	public ArAaRelId() {
	}

	public ArAaRelId(int actor1Id, int actor2Id, short type) {
		this.actor1Id = actor1Id;
		this.actor2Id = actor2Id;
		this.type = type;
	}

	@Column(name = "ACTOR1_ID", nullable = false)
	public int getActor1Id() {
		return this.actor1Id;
	}

	public void setActor1Id(int actor1Id) {
		this.actor1Id = actor1Id;
	}

	@Column(name = "ACTOR2_ID", nullable = false)
	public int getActor2Id() {
		return this.actor2Id;
	}

	public void setActor2Id(int actor2Id) {
		this.actor2Id = actor2Id;
	}

	@Column(name = "TYPE", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArAaRelId))
			return false;
		ArAaRelId castOther = (ArAaRelId) other;

		return (this.getActor1Id() == castOther.getActor1Id())
				&& (this.getActor2Id() == castOther.getActor2Id())
				&& (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActor1Id();
		result = 37 * result + this.getActor2Id();
		result = 37 * result + this.getType();
		return result;
	}

}
