package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArAaRel generated by hbm2java
 */
@Entity
@Table(name = "AR_AA_REL", schema = "dbo", catalog = "alkotest")
public class ArAaRel implements java.io.Serializable {

	private ArAaRelId id;

	private ArActor arActorByActor1Id;

	private ArActor arActorByActor2Id;

	private Date insTime;

	private Date updTime;

	private String descr;

	private Set<ArDocAddActperm> arDocAddActperms = new HashSet<ArDocAddActperm>(
			0);

	public ArAaRel() {
	}

	public ArAaRel(ArAaRelId id, ArActor arActorByActor1Id,
			ArActor arActorByActor2Id, Date insTime, Date updTime) {
		this.id = id;
		this.arActorByActor1Id = arActorByActor1Id;
		this.arActorByActor2Id = arActorByActor2Id;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArAaRel(ArAaRelId id, ArActor arActorByActor1Id,
			ArActor arActorByActor2Id, Date insTime, Date updTime,
			String descr, Set<ArDocAddActperm> arDocAddActperms) {
		this.id = id;
		this.arActorByActor1Id = arActorByActor1Id;
		this.arActorByActor2Id = arActorByActor2Id;
		this.insTime = insTime;
		this.updTime = updTime;
		this.descr = descr;
		this.arDocAddActperms = arDocAddActperms;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "actor1Id", column = @Column(name = "ACTOR1_ID", nullable = false)),
			@AttributeOverride(name = "actor2Id", column = @Column(name = "ACTOR2_ID", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "TYPE", nullable = false)) })
	public ArAaRelId getId() {
		return this.id;
	}

	public void setId(ArAaRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTOR1_ID", nullable = false, insertable = false, updatable = false)
	public ArActor getArActorByActor1Id() {
		return this.arActorByActor1Id;
	}

	public void setArActorByActor1Id(ArActor arActorByActor1Id) {
		this.arActorByActor1Id = arActorByActor1Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTOR2_ID", nullable = false, insertable = false, updatable = false)
	public ArActor getArActorByActor2Id() {
		return this.arActorByActor2Id;
	}

	public void setArActorByActor2Id(ArActor arActorByActor2Id) {
		this.arActorByActor2Id = arActorByActor2Id;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "DESCR", length = 50)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arAaRel")
	public Set<ArDocAddActperm> getArDocAddActperms() {
		return this.arDocAddActperms;
	}

	public void setArDocAddActperms(Set<ArDocAddActperm> arDocAddActperms) {
		this.arDocAddActperms = arDocAddActperms;
	}

}
