package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArAbort generated by hbm2java
 */
@Entity
@Table(name = "AR_ABORT", schema = "dbo", catalog = "alkotest")
public class ArAbort implements java.io.Serializable {

	private byte abort;

	public ArAbort() {
	}

	public ArAbort(byte abort) {
		this.abort = abort;
	}

	@Id
	@Column(name = "ABORT", unique = true, nullable = false)
	public byte getAbort() {
		return this.abort;
	}

	public void setAbort(byte abort) {
		this.abort = abort;
	}

}
