package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArActor generated by hbm2java
 */
@Entity
@Table(name = "AR_ACTOR", schema = "dbo", catalog = "alkotest")
public class ArActor implements java.io.Serializable {

	private int id;

	private ArActorAddCont arActorAddCont;

	private String name;

	private String forenames;

	private String code;

	private String systemUserName;

	private Date insTime;

	private Date updTime;

	private int flags;

	private String astorageLnr;

	private String ackDecision;

	private String regNr;

	private Date ackDecisionTime;

	private Set<ArAaRel> arAaRelsForActor2Id = new HashSet<ArAaRel>(0);

	private Set<ArDocAddAppl> arDocAddApplsForManActorId = new HashSet<ArDocAddAppl>(
			0);

	private Set<ArWwwDocActperm> arWwwDocActpermsForResActorId = new HashSet<ArWwwDocActperm>(
			0);

	private Set<ArDocAddAppl> arDocAddApplsForAppActorId = new HashSet<ArDocAddAppl>(
			0);

	private Set<ArActorAddCont> arActorAddConts = new HashSet<ArActorAddCont>(0);

	private Set<ArItemMov> arItemMovs = new HashSet<ArItemMov>(0);

	private Set<ArDocAddBlading> arDocAddBladings = new HashSet<ArDocAddBlading>(
			0);

	private Set<ArDocAddEnquiry> arDocAddEnquiriesForEnActorId = new HashSet<ArDocAddEnquiry>(
			0);

	private Set<ArWwwDocActperm> arWwwDocActpermsForDstActorId = new HashSet<ArWwwDocActperm>(
			0);

	private Set<ArWwwDocActperm> arWwwDocActpermsForIssActorId = new HashSet<ArWwwDocActperm>(
			0);

	private Set<ArAaRel> arAaRelsForActor1Id = new HashSet<ArAaRel>(0);

	private Set<ArDocAddEnquiry> arDocAddEnquiriesForRpActorId = new HashSet<ArDocAddEnquiry>(
			0);

	private Set<ArDocAddActperm> arDocAddActperms = new HashSet<ArDocAddActperm>(
			0);

	private Set<ArDocAddStat> arDocAddStats = new HashSet<ArDocAddStat>(0);

	public ArActor() {
	}

	public ArActor(int id, String name, Date insTime, Date updTime, int flags) {
		this.id = id;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArActor(int id, ArActorAddCont arActorAddCont, String name,
			String forenames, String code, String systemUserName, Date insTime,
			Date updTime, int flags, String astorageLnr, String ackDecision,
			String regNr, Date ackDecisionTime,
			Set<ArAaRel> arAaRelsForActor2Id,
			Set<ArDocAddAppl> arDocAddApplsForManActorId,
			Set<ArWwwDocActperm> arWwwDocActpermsForResActorId,
			Set<ArDocAddAppl> arDocAddApplsForAppActorId,
			Set<ArActorAddCont> arActorAddConts, Set<ArItemMov> arItemMovs,
			Set<ArDocAddBlading> arDocAddBladings,
			Set<ArDocAddEnquiry> arDocAddEnquiriesForEnActorId,
			Set<ArWwwDocActperm> arWwwDocActpermsForDstActorId,
			Set<ArWwwDocActperm> arWwwDocActpermsForIssActorId,
			Set<ArAaRel> arAaRelsForActor1Id,
			Set<ArDocAddEnquiry> arDocAddEnquiriesForRpActorId,
			Set<ArDocAddActperm> arDocAddActperms,
			Set<ArDocAddStat> arDocAddStats) {
		this.id = id;
		this.arActorAddCont = arActorAddCont;
		this.name = name;
		this.forenames = forenames;
		this.code = code;
		this.systemUserName = systemUserName;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.astorageLnr = astorageLnr;
		this.ackDecision = ackDecision;
		this.regNr = regNr;
		this.ackDecisionTime = ackDecisionTime;
		this.arAaRelsForActor2Id = arAaRelsForActor2Id;
		this.arDocAddApplsForManActorId = arDocAddApplsForManActorId;
		this.arWwwDocActpermsForResActorId = arWwwDocActpermsForResActorId;
		this.arDocAddApplsForAppActorId = arDocAddApplsForAppActorId;
		this.arActorAddConts = arActorAddConts;
		this.arItemMovs = arItemMovs;
		this.arDocAddBladings = arDocAddBladings;
		this.arDocAddEnquiriesForEnActorId = arDocAddEnquiriesForEnActorId;
		this.arWwwDocActpermsForDstActorId = arWwwDocActpermsForDstActorId;
		this.arWwwDocActpermsForIssActorId = arWwwDocActpermsForIssActorId;
		this.arAaRelsForActor1Id = arAaRelsForActor1Id;
		this.arDocAddEnquiriesForRpActorId = arDocAddEnquiriesForRpActorId;
		this.arDocAddActperms = arDocAddActperms;
		this.arDocAddStats = arDocAddStats;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ACTOR_ADD_CONT_ID_DEF")
	public ArActorAddCont getArActorAddCont() {
		return this.arActorAddCont;
	}

	public void setArActorAddCont(ArActorAddCont arActorAddCont) {
		this.arActorAddCont = arActorAddCont;
	}

	@Column(name = "NAME", nullable = false, length = 170)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FORENAMES", length = 100)
	public String getForenames() {
		return this.forenames;
	}

	public void setForenames(String forenames) {
		this.forenames = forenames;
	}

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "SYSTEM_USER_NAME")
	public String getSystemUserName() {
		return this.systemUserName;
	}

	public void setSystemUserName(String systemUserName) {
		this.systemUserName = systemUserName;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "ASTORAGE_LNR", length = 64)
	public String getAstorageLnr() {
		return this.astorageLnr;
	}

	public void setAstorageLnr(String astorageLnr) {
		this.astorageLnr = astorageLnr;
	}

	@Column(name = "ACK_DECISION", length = 64)
	public String getAckDecision() {
		return this.ackDecision;
	}

	public void setAckDecision(String ackDecision) {
		this.ackDecision = ackDecision;
	}

	@Column(name = "REG_NR", length = 64)
	public String getRegNr() {
		return this.regNr;
	}

	public void setRegNr(String regNr) {
		this.regNr = regNr;
	}

	@Column(name = "ACK_DECISION_TIME", length = 23)
	public Date getAckDecisionTime() {
		return this.ackDecisionTime;
	}

	public void setAckDecisionTime(Date ackDecisionTime) {
		this.ackDecisionTime = ackDecisionTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByActor2Id")
	public Set<ArAaRel> getArAaRelsForActor2Id() {
		return this.arAaRelsForActor2Id;
	}

	public void setArAaRelsForActor2Id(Set<ArAaRel> arAaRelsForActor2Id) {
		this.arAaRelsForActor2Id = arAaRelsForActor2Id;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByManActorId")
	public Set<ArDocAddAppl> getArDocAddApplsForManActorId() {
		return this.arDocAddApplsForManActorId;
	}

	public void setArDocAddApplsForManActorId(
			Set<ArDocAddAppl> arDocAddApplsForManActorId) {
		this.arDocAddApplsForManActorId = arDocAddApplsForManActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByResActorId")
	public Set<ArWwwDocActperm> getArWwwDocActpermsForResActorId() {
		return this.arWwwDocActpermsForResActorId;
	}

	public void setArWwwDocActpermsForResActorId(
			Set<ArWwwDocActperm> arWwwDocActpermsForResActorId) {
		this.arWwwDocActpermsForResActorId = arWwwDocActpermsForResActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByAppActorId")
	public Set<ArDocAddAppl> getArDocAddApplsForAppActorId() {
		return this.arDocAddApplsForAppActorId;
	}

	public void setArDocAddApplsForAppActorId(
			Set<ArDocAddAppl> arDocAddApplsForAppActorId) {
		this.arDocAddApplsForAppActorId = arDocAddApplsForAppActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActor")
	public Set<ArActorAddCont> getArActorAddConts() {
		return this.arActorAddConts;
	}

	public void setArActorAddConts(Set<ArActorAddCont> arActorAddConts) {
		this.arActorAddConts = arActorAddConts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActor")
	public Set<ArItemMov> getArItemMovs() {
		return this.arItemMovs;
	}

	public void setArItemMovs(Set<ArItemMov> arItemMovs) {
		this.arItemMovs = arItemMovs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActor")
	public Set<ArDocAddBlading> getArDocAddBladings() {
		return this.arDocAddBladings;
	}

	public void setArDocAddBladings(Set<ArDocAddBlading> arDocAddBladings) {
		this.arDocAddBladings = arDocAddBladings;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByEnActorId")
	public Set<ArDocAddEnquiry> getArDocAddEnquiriesForEnActorId() {
		return this.arDocAddEnquiriesForEnActorId;
	}

	public void setArDocAddEnquiriesForEnActorId(
			Set<ArDocAddEnquiry> arDocAddEnquiriesForEnActorId) {
		this.arDocAddEnquiriesForEnActorId = arDocAddEnquiriesForEnActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByDstActorId")
	public Set<ArWwwDocActperm> getArWwwDocActpermsForDstActorId() {
		return this.arWwwDocActpermsForDstActorId;
	}

	public void setArWwwDocActpermsForDstActorId(
			Set<ArWwwDocActperm> arWwwDocActpermsForDstActorId) {
		this.arWwwDocActpermsForDstActorId = arWwwDocActpermsForDstActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByIssActorId")
	public Set<ArWwwDocActperm> getArWwwDocActpermsForIssActorId() {
		return this.arWwwDocActpermsForIssActorId;
	}

	public void setArWwwDocActpermsForIssActorId(
			Set<ArWwwDocActperm> arWwwDocActpermsForIssActorId) {
		this.arWwwDocActpermsForIssActorId = arWwwDocActpermsForIssActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByActor1Id")
	public Set<ArAaRel> getArAaRelsForActor1Id() {
		return this.arAaRelsForActor1Id;
	}

	public void setArAaRelsForActor1Id(Set<ArAaRel> arAaRelsForActor1Id) {
		this.arAaRelsForActor1Id = arAaRelsForActor1Id;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorByRpActorId")
	public Set<ArDocAddEnquiry> getArDocAddEnquiriesForRpActorId() {
		return this.arDocAddEnquiriesForRpActorId;
	}

	public void setArDocAddEnquiriesForRpActorId(
			Set<ArDocAddEnquiry> arDocAddEnquiriesForRpActorId) {
		this.arDocAddEnquiriesForRpActorId = arDocAddEnquiriesForRpActorId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActor")
	public Set<ArDocAddActperm> getArDocAddActperms() {
		return this.arDocAddActperms;
	}

	public void setArDocAddActperms(Set<ArDocAddActperm> arDocAddActperms) {
		this.arDocAddActperms = arDocAddActperms;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActor")
	public Set<ArDocAddStat> getArDocAddStats() {
		return this.arDocAddStats;
	}

	public void setArDocAddStats(Set<ArDocAddStat> arDocAddStats) {
		this.arDocAddStats = arDocAddStats;
	}

}
