package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArActorAddCont generated by hbm2java
 */
@Entity
@Table(name = "AR_ACTOR_ADD_CONT", schema = "dbo", catalog = "alkotest")
public class ArActorAddCont implements java.io.Serializable {

	private int id;

	private ArCountry arCountry;

	private ArActor arActor;

	private String state;

	private String city;

	private String address;

	private String zip;

	private String phone;

	private String fax;

	private String email;

	private Date insTime;

	private Date updTime;

	private int flags;

	private Set<ArDocAddActperm> arDocAddActperms = new HashSet<ArDocAddActperm>(
			0);

	private Set<ArItemMov> arItemMovs = new HashSet<ArItemMov>(0);

	private Set<ArActor> arActors = new HashSet<ArActor>(0);

	public ArActorAddCont() {
	}

	public ArActorAddCont(int id, ArActor arActor, Date insTime, Date updTime,
			int flags) {
		this.id = id;
		this.arActor = arActor;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArActorAddCont(int id, ArCountry arCountry, ArActor arActor,
			String state, String city, String address, String zip,
			String phone, String fax, String email, Date insTime, Date updTime,
			int flags, Set<ArDocAddActperm> arDocAddActperms,
			Set<ArItemMov> arItemMovs, Set<ArActor> arActors) {
		this.id = id;
		this.arCountry = arCountry;
		this.arActor = arActor;
		this.state = state;
		this.city = city;
		this.address = address;
		this.zip = zip;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.arDocAddActperms = arDocAddActperms;
		this.arItemMovs = arItemMovs;
		this.arActors = arActors;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COUNTRY_ID")
	public ArCountry getArCountry() {
		return this.arCountry;
	}

	public void setArCountry(ArCountry arCountry) {
		this.arCountry = arCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTOR_ID", nullable = false)
	public ArActor getArActor() {
		return this.arActor;
	}

	public void setArActor(ArActor arActor) {
		this.arActor = arActor;
	}

	@Column(name = "STATE", length = 35)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CITY", length = 35)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "ZIP", length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "PHONE", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "FAX", length = 100)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorAddCont")
	public Set<ArDocAddActperm> getArDocAddActperms() {
		return this.arDocAddActperms;
	}

	public void setArDocAddActperms(Set<ArDocAddActperm> arDocAddActperms) {
		this.arDocAddActperms = arDocAddActperms;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorAddCont")
	public Set<ArItemMov> getArItemMovs() {
		return this.arItemMovs;
	}

	public void setArItemMovs(Set<ArItemMov> arItemMovs) {
		this.arItemMovs = arItemMovs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActorAddCont")
	public Set<ArActor> getArActors() {
		return this.arActors;
	}

	public void setArActors(Set<ArActor> arActors) {
		this.arActors = arActors;
	}

}
