package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArActpermType generated by hbm2java
 */
@Entity
@Table(name = "AR_ACTPERM_TYPE", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class ArActpermType implements java.io.Serializable {

	private int id;

	private String name;

	private Date insTime;

	private Date updTime;

	private int flags;

	private int contMask;

	private Set<ArWwwDocActperm> arWwwDocActperms = new HashSet<ArWwwDocActperm>(
			0);

	private Set<ArDocAddActperm> arDocAddActperms = new HashSet<ArDocAddActperm>(
			0);

	public ArActpermType() {
	}

	public ArActpermType(int id, String name, Date insTime, Date updTime,
			int flags, int contMask) {
		this.id = id;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.contMask = contMask;
	}

	public ArActpermType(int id, String name, Date insTime, Date updTime,
			int flags, int contMask, Set<ArWwwDocActperm> arWwwDocActperms,
			Set<ArDocAddActperm> arDocAddActperms) {
		this.id = id;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.contMask = contMask;
		this.arWwwDocActperms = arWwwDocActperms;
		this.arDocAddActperms = arDocAddActperms;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "CONT_MASK", nullable = false)
	public int getContMask() {
		return this.contMask;
	}

	public void setContMask(int contMask) {
		this.contMask = contMask;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActpermType")
	public Set<ArWwwDocActperm> getArWwwDocActperms() {
		return this.arWwwDocActperms;
	}

	public void setArWwwDocActperms(Set<ArWwwDocActperm> arWwwDocActperms) {
		this.arWwwDocActperms = arWwwDocActperms;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arActpermType")
	public Set<ArDocAddActperm> getArDocAddActperms() {
		return this.arDocAddActperms;
	}

	public void setArDocAddActperms(Set<ArDocAddActperm> arDocAddActperms) {
		this.arDocAddActperms = arDocAddActperms;
	}

}
