package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArCityLookup generated by hbm2java
 */
@Entity
@Table(name = "AR_CITY_LOOKUP", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = "CITY"))
public class ArCityLookup implements java.io.Serializable {

	private int id;

	private String city;

	private String state;

	private Date insTime;

	private Date updTime;

	private int flags;

	public ArCityLookup() {
	}

	public ArCityLookup(int id, String city, Date insTime, Date updTime,
			int flags) {
		this.id = id;
		this.city = city;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArCityLookup(int id, String city, String state, Date insTime,
			Date updTime, int flags) {
		this.id = id;
		this.city = city;
		this.state = state;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CITY", unique = true, nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
