package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArClientLogin generated by hbm2java
 */
@Entity
@Table(name = "AR_CLIENT_LOGIN", schema = "dbo", catalog = "alkotest")
public class ArClientLogin implements java.io.Serializable {

	private int id;

	private Date insTime;

	private String systemUserName;

	private String app;

	private String build;

	private String host;

	private int spid;

	public ArClientLogin() {
	}

	public ArClientLogin(int id, Date insTime, String systemUserName, int spid) {
		this.id = id;
		this.insTime = insTime;
		this.systemUserName = systemUserName;
		this.spid = spid;
	}

	public ArClientLogin(int id, Date insTime, String systemUserName,
			String app, String build, String host, int spid) {
		this.id = id;
		this.insTime = insTime;
		this.systemUserName = systemUserName;
		this.app = app;
		this.build = build;
		this.host = host;
		this.spid = spid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "SYSTEM_USER_NAME", nullable = false, length = 128)
	public String getSystemUserName() {
		return this.systemUserName;
	}

	public void setSystemUserName(String systemUserName) {
		this.systemUserName = systemUserName;
	}

	@Column(name = "APP", length = 128)
	public String getApp() {
		return this.app;
	}

	public void setApp(String app) {
		this.app = app;
	}

	@Column(name = "BUILD", length = 128)
	public String getBuild() {
		return this.build;
	}

	public void setBuild(String build) {
		this.build = build;
	}

	@Column(name = "HOST", length = 128)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "SPID", nullable = false)
	public int getSpid() {
		return this.spid;
	}

	public void setSpid(int spid) {
		this.spid = spid;
	}

}
