package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArCountry generated by hbm2java
 */
@Entity
@Table(name = "AR_COUNTRY", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class ArCountry implements java.io.Serializable {

	private int id;

	private String name;

	private String iso2;

	private String iso3;

	private String remarks;

	private Date insTime;

	private Date updTime;

	private int flags;

	private Set<ArItem> arItems = new HashSet<ArItem>(0);

	private Set<ArActorAddCont> arActorAddConts = new HashSet<ArActorAddCont>(0);

	public ArCountry() {
	}

	public ArCountry(int id, String name, Date insTime, Date updTime, int flags) {
		this.id = id;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArCountry(int id, String name, String iso2, String iso3,
			String remarks, Date insTime, Date updTime, int flags,
			Set<ArItem> arItems, Set<ArActorAddCont> arActorAddConts) {
		this.id = id;
		this.name = name;
		this.iso2 = iso2;
		this.iso3 = iso3;
		this.remarks = remarks;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.arItems = arItems;
		this.arActorAddConts = arActorAddConts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ISO2", length = 2)
	public String getIso2() {
		return this.iso2;
	}

	public void setIso2(String iso2) {
		this.iso2 = iso2;
	}

	@Column(name = "ISO3", length = 3)
	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arCountry")
	public Set<ArItem> getArItems() {
		return this.arItems;
	}

	public void setArItems(Set<ArItem> arItems) {
		this.arItems = arItems;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arCountry")
	public Set<ArActorAddCont> getArActorAddConts() {
		return this.arActorAddConts;
	}

	public void setArActorAddConts(Set<ArActorAddCont> arActorAddConts) {
		this.arActorAddConts = arActorAddConts;
	}

}
