package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArCommiprotVoteId generated by hbm2java
 */
@Embeddable
public class ArCommiprotVoteId implements java.io.Serializable {

	private String protNr;

	private int AId;

	private int docAddCommiprotId;

	public ArCommiprotVoteId() {
	}

	public ArCommiprotVoteId(String protNr, int AId, int docAddCommiprotId) {
		this.protNr = protNr;
		this.AId = AId;
		this.docAddCommiprotId = docAddCommiprotId;
	}

	@Column(name = "PROT_NR", nullable = false, length = 50)
	public String getProtNr() {
		return this.protNr;
	}

	public void setProtNr(String protNr) {
		this.protNr = protNr;
	}

	@Column(name = "A_ID", nullable = false)
	public int getAId() {
		return this.AId;
	}

	public void setAId(int AId) {
		this.AId = AId;
	}

	@Column(name = "DOC_ADD_COMMIPROT_ID", nullable = false)
	public int getDocAddCommiprotId() {
		return this.docAddCommiprotId;
	}

	public void setDocAddCommiprotId(int docAddCommiprotId) {
		this.docAddCommiprotId = docAddCommiprotId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArCommiprotVoteId))
			return false;
		ArCommiprotVoteId castOther = (ArCommiprotVoteId) other;

		return ((this.getProtNr() == castOther.getProtNr()) || (this
				.getProtNr() != null
				&& castOther.getProtNr() != null && this.getProtNr().equals(
				castOther.getProtNr())))
				&& (this.getAId() == castOther.getAId())
				&& (this.getDocAddCommiprotId() == castOther
						.getDocAddCommiprotId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProtNr() == null ? 0 : this.getProtNr().hashCode());
		result = 37 * result + this.getAId();
		result = 37 * result + this.getDocAddCommiprotId();
		return result;
	}

}
