package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArCommiprotVote generated by hbm2java
 */
@Entity
@Table(name = "AR_COMMIPROT_VOTE", schema = "dbo", catalog = "alkotest")
public class ArCommiprotVote implements java.io.Serializable {

	private ArCommiprotVoteId id;

	private ArCommeetingParticip arCommeetingParticip;

	private ArDocAddCommiprot arDocAddCommiprot;

	private byte vote;

	private Date insTime;

	private Date updTime;

	private int flags;

	public ArCommiprotVote() {
	}

	public ArCommiprotVote(ArCommiprotVoteId id,
			ArCommeetingParticip arCommeetingParticip,
			ArDocAddCommiprot arDocAddCommiprot, byte vote, Date insTime,
			Date updTime, int flags) {
		this.id = id;
		this.arCommeetingParticip = arCommeetingParticip;
		this.arDocAddCommiprot = arDocAddCommiprot;
		this.vote = vote;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "protNr", column = @Column(name = "PROT_NR", nullable = false, length = 50)),
			@AttributeOverride(name = "AId", column = @Column(name = "A_ID", nullable = false)),
			@AttributeOverride(name = "docAddCommiprotId", column = @Column(name = "DOC_ADD_COMMIPROT_ID", nullable = false)) })
	public ArCommiprotVoteId getId() {
		return this.id;
	}

	public void setId(ArCommiprotVoteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "PROT_NR", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "A_ID", nullable = false, insertable = false, updatable = false) })
	public ArCommeetingParticip getArCommeetingParticip() {
		return this.arCommeetingParticip;
	}

	public void setArCommeetingParticip(
			ArCommeetingParticip arCommeetingParticip) {
		this.arCommeetingParticip = arCommeetingParticip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_ADD_COMMIPROT_ID", nullable = false, insertable = false, updatable = false)
	public ArDocAddCommiprot getArDocAddCommiprot() {
		return this.arDocAddCommiprot;
	}

	public void setArDocAddCommiprot(ArDocAddCommiprot arDocAddCommiprot) {
		this.arDocAddCommiprot = arDocAddCommiprot;
	}

	@Column(name = "VOTE", nullable = false)
	public byte getVote() {
		return this.vote;
	}

	public void setVote(byte vote) {
		this.vote = vote;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
