package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArCommeeting generated by hbm2java
 */
@Entity
@Table(name = "AR_COMMEETING", schema = "dbo", catalog = "alkotest")
public class ArCommeeting implements java.io.Serializable {

	private String protNr;

	private String protName;

	private Date meetingStart;

	private Date meetingEnd;

	private Date insTime;

	private Date updTime;

	private Set<ArDocAddCommiprot> arDocAddCommiprots = new HashSet<ArDocAddCommiprot>(
			0);

	private Set<ArCommeetingParticip> arCommeetingParticips = new HashSet<ArCommeetingParticip>(
			0);

	public ArCommeeting() {
	}

	public ArCommeeting(String protNr, String protName, Date meetingStart,
			Date insTime, Date updTime) {
		this.protNr = protNr;
		this.protName = protName;
		this.meetingStart = meetingStart;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArCommeeting(String protNr, String protName, Date meetingStart,
			Date meetingEnd, Date insTime, Date updTime,
			Set<ArDocAddCommiprot> arDocAddCommiprots,
			Set<ArCommeetingParticip> arCommeetingParticips) {
		this.protNr = protNr;
		this.protName = protName;
		this.meetingStart = meetingStart;
		this.meetingEnd = meetingEnd;
		this.insTime = insTime;
		this.updTime = updTime;
		this.arDocAddCommiprots = arDocAddCommiprots;
		this.arCommeetingParticips = arCommeetingParticips;
	}

	@Id
	@Column(name = "PROT_NR", unique = true, nullable = false, length = 50)
	public String getProtNr() {
		return this.protNr;
	}

	public void setProtNr(String protNr) {
		this.protNr = protNr;
	}

	@Column(name = "PROT_NAME", nullable = false)
	public String getProtName() {
		return this.protName;
	}

	public void setProtName(String protName) {
		this.protName = protName;
	}

	@Column(name = "MEETING_START", nullable = false, length = 23)
	public Date getMeetingStart() {
		return this.meetingStart;
	}

	public void setMeetingStart(Date meetingStart) {
		this.meetingStart = meetingStart;
	}

	@Column(name = "MEETING_END", length = 23)
	public Date getMeetingEnd() {
		return this.meetingEnd;
	}

	public void setMeetingEnd(Date meetingEnd) {
		this.meetingEnd = meetingEnd;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arCommeeting")
	public Set<ArDocAddCommiprot> getArDocAddCommiprots() {
		return this.arDocAddCommiprots;
	}

	public void setArDocAddCommiprots(Set<ArDocAddCommiprot> arDocAddCommiprots) {
		this.arDocAddCommiprots = arDocAddCommiprots;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arCommeeting")
	public Set<ArCommeetingParticip> getArCommeetingParticips() {
		return this.arCommeetingParticips;
	}

	public void setArCommeetingParticips(
			Set<ArCommeetingParticip> arCommeetingParticips) {
		this.arCommeetingParticips = arCommeetingParticips;
	}

}
