package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArCommeetingParticip generated by hbm2java
 */
@Entity
@Table(name = "AR_COMMEETING_PARTICIP", schema = "dbo", catalog = "alkotest")
public class ArCommeetingParticip implements java.io.Serializable {

	private ArCommeetingParticipId id;

	private ArCommeeting arCommeeting;

	private int role;

	private Date insTime;

	private Date updTime;

	private Set<ArCommiprotVote> arCommiprotVotes = new HashSet<ArCommiprotVote>(
			0);

	public ArCommeetingParticip() {
	}

	public ArCommeetingParticip(ArCommeetingParticipId id,
			ArCommeeting arCommeeting, int role, Date insTime, Date updTime) {
		this.id = id;
		this.arCommeeting = arCommeeting;
		this.role = role;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArCommeetingParticip(ArCommeetingParticipId id,
			ArCommeeting arCommeeting, int role, Date insTime, Date updTime,
			Set<ArCommiprotVote> arCommiprotVotes) {
		this.id = id;
		this.arCommeeting = arCommeeting;
		this.role = role;
		this.insTime = insTime;
		this.updTime = updTime;
		this.arCommiprotVotes = arCommiprotVotes;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "protNr", column = @Column(name = "PROT_NR", nullable = false, length = 50)),
			@AttributeOverride(name = "AId", column = @Column(name = "A_ID", nullable = false)) })
	public ArCommeetingParticipId getId() {
		return this.id;
	}

	public void setId(ArCommeetingParticipId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROT_NR", nullable = false, insertable = false, updatable = false)
	public ArCommeeting getArCommeeting() {
		return this.arCommeeting;
	}

	public void setArCommeeting(ArCommeeting arCommeeting) {
		this.arCommeeting = arCommeeting;
	}

	@Column(name = "ROLE", nullable = false)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arCommeetingParticip")
	public Set<ArCommiprotVote> getArCommiprotVotes() {
		return this.arCommiprotVotes;
	}

	public void setArCommiprotVotes(Set<ArCommiprotVote> arCommiprotVotes) {
		this.arCommiprotVotes = arCommiprotVotes;
	}

}
