package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArCommeetingParticipId generated by hbm2java
 */
@Embeddable
public class ArCommeetingParticipId implements java.io.Serializable {

	private String protNr;

	private int AId;

	public ArCommeetingParticipId() {
	}

	public ArCommeetingParticipId(String protNr, int AId) {
		this.protNr = protNr;
		this.AId = AId;
	}

	@Column(name = "PROT_NR", nullable = false, length = 50)
	public String getProtNr() {
		return this.protNr;
	}

	public void setProtNr(String protNr) {
		this.protNr = protNr;
	}

	@Column(name = "A_ID", nullable = false)
	public int getAId() {
		return this.AId;
	}

	public void setAId(int AId) {
		this.AId = AId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArCommeetingParticipId))
			return false;
		ArCommeetingParticipId castOther = (ArCommeetingParticipId) other;

		return ((this.getProtNr() == castOther.getProtNr()) || (this
				.getProtNr() != null
				&& castOther.getProtNr() != null && this.getProtNr().equals(
				castOther.getProtNr())))
				&& (this.getAId() == castOther.getAId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProtNr() == null ? 0 : this.getProtNr().hashCode());
		result = 37 * result + this.getAId();
		return result;
	}

}
