package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArDocAddEnquiry generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_ENQUIRY", schema = "dbo", catalog = "alkotest")
public class ArDocAddEnquiry implements java.io.Serializable {

	private int id;

	private ArActor arActorByEnActorId;

	private ArActor arActorByRpActorId;

	private Date recTime;

	private int docNr;

	private String enText;

	private byte[] enImg;

	private String refYours;

	private int rp;

	private String rpText;

	private Date rpRecTime;

	private String refOurs;

	private Date insTime;

	private Date updTime;

	public ArDocAddEnquiry() {
	}

	public ArDocAddEnquiry(int id, ArActor arActorByEnActorId, Date recTime,
			int docNr, int rp, Date insTime, Date updTime) {
		this.id = id;
		this.arActorByEnActorId = arActorByEnActorId;
		this.recTime = recTime;
		this.docNr = docNr;
		this.rp = rp;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArDocAddEnquiry(int id, ArActor arActorByEnActorId,
			ArActor arActorByRpActorId, Date recTime, int docNr, String enText,
			byte[] enImg, String refYours, int rp, String rpText,
			Date rpRecTime, String refOurs, Date insTime, Date updTime) {
		this.id = id;
		this.arActorByEnActorId = arActorByEnActorId;
		this.arActorByRpActorId = arActorByRpActorId;
		this.recTime = recTime;
		this.docNr = docNr;
		this.enText = enText;
		this.enImg = enImg;
		this.refYours = refYours;
		this.rp = rp;
		this.rpText = rpText;
		this.rpRecTime = rpRecTime;
		this.refOurs = refOurs;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EN_ACTOR_ID", nullable = false)
	public ArActor getArActorByEnActorId() {
		return this.arActorByEnActorId;
	}

	public void setArActorByEnActorId(ArActor arActorByEnActorId) {
		this.arActorByEnActorId = arActorByEnActorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RP_ACTOR_ID")
	public ArActor getArActorByRpActorId() {
		return this.arActorByRpActorId;
	}

	public void setArActorByRpActorId(ArActor arActorByRpActorId) {
		this.arActorByRpActorId = arActorByRpActorId;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "EN_TEXT")
	public String getEnText() {
		return this.enText;
	}

	public void setEnText(String enText) {
		this.enText = enText;
	}

	@Column(name = "EN_IMG")
	public byte[] getEnImg() {
		return this.enImg;
	}

	public void setEnImg(byte[] enImg) {
		this.enImg = enImg;
	}

	@Column(name = "REF_YOURS", length = 50)
	public String getRefYours() {
		return this.refYours;
	}

	public void setRefYours(String refYours) {
		this.refYours = refYours;
	}

	@Column(name = "RP", nullable = false)
	public int getRp() {
		return this.rp;
	}

	public void setRp(int rp) {
		this.rp = rp;
	}

	@Column(name = "RP_TEXT")
	public String getRpText() {
		return this.rpText;
	}

	public void setRpText(String rpText) {
		this.rpText = rpText;
	}

	@Column(name = "RP_REC_TIME", length = 23)
	public Date getRpRecTime() {
		return this.rpRecTime;
	}

	public void setRpRecTime(Date rpRecTime) {
		this.rpRecTime = rpRecTime;
	}

	@Column(name = "REF_OURS", length = 50)
	public String getRefOurs() {
		return this.refOurs;
	}

	public void setRefOurs(String refOurs) {
		this.refOurs = refOurs;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
