package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArDocAddStat generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_STAT", schema = "dbo", catalog = "alkotest")
public class ArDocAddStat implements java.io.Serializable {

	private int id;

	private ArItem arItem;

	private ArActor arActor;

	private Date recTime;

	private int docNr;

	private Date insTime;

	private Date updTime;

	private int flags;

	public ArDocAddStat() {
	}

	public ArDocAddStat(int id, ArItem arItem, ArActor arActor, Date recTime,
			int docNr, Date insTime, Date updTime, int flags) {
		this.id = id;
		this.arItem = arItem;
		this.arActor = arActor;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public ArItem getArItem() {
		return this.arItem;
	}

	public void setArItem(ArItem arItem) {
		this.arItem = arItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DST_ACTOR_ID", nullable = false)
	public ArActor getArActor() {
		return this.arActor;
	}

	public void setArActor(ArActor arActor) {
		this.arActor = arActor;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
