package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArDocAddCommiprot generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_COMMIPROT", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DOC_ADD_APPL_ID", "UK_HELPER" }))
public class ArDocAddCommiprot implements java.io.Serializable {

	private int id;

	private ArDocAddAppl arDocAddAppl;

	private ArCommeeting arCommeeting;

	private Date recTime;

	private int docNr;

	private Date insTime;

	private Date updTime;

	private Date proTime;

	private short decisionAnal;

	private String decisionStory;

	private short decisionItem;

	private String decisionItemStory;

	private String regBookNr;

	private int flags;

	private String valisOsaleja;

	private String sqnavqtud;

	private Integer haaletusPoolt;

	private Integer haaletusVastu;

	private String eriarvamused;

	private Integer pkpNr;

	private Short decisionTestItem;

	private String decisionTestItemStory;

	private String decisionNr;

	private int ukHelper;

	private Set<ArCommiprotVote> arCommiprotVotes = new HashSet<ArCommiprotVote>(
			0);

	public ArDocAddCommiprot() {
	}

	public ArDocAddCommiprot(int id, ArDocAddAppl arDocAddAppl, Date recTime,
			int docNr, Date insTime, Date updTime, Date proTime,
			short decisionAnal, short decisionItem, int flags, int ukHelper) {
		this.id = id;
		this.arDocAddAppl = arDocAddAppl;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.proTime = proTime;
		this.decisionAnal = decisionAnal;
		this.decisionItem = decisionItem;
		this.flags = flags;
		this.ukHelper = ukHelper;
	}

	public ArDocAddCommiprot(int id, ArDocAddAppl arDocAddAppl,
			ArCommeeting arCommeeting, Date recTime, int docNr, Date insTime,
			Date updTime, Date proTime, short decisionAnal,
			String decisionStory, short decisionItem, String decisionItemStory,
			String regBookNr, int flags, String valisOsaleja, String sqnavqtud,
			Integer haaletusPoolt, Integer haaletusVastu, String eriarvamused,
			Integer pkpNr, Short decisionTestItem,
			String decisionTestItemStory, String decisionNr, int ukHelper,
			Set<ArCommiprotVote> arCommiprotVotes) {
		this.id = id;
		this.arDocAddAppl = arDocAddAppl;
		this.arCommeeting = arCommeeting;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.proTime = proTime;
		this.decisionAnal = decisionAnal;
		this.decisionStory = decisionStory;
		this.decisionItem = decisionItem;
		this.decisionItemStory = decisionItemStory;
		this.regBookNr = regBookNr;
		this.flags = flags;
		this.valisOsaleja = valisOsaleja;
		this.sqnavqtud = sqnavqtud;
		this.haaletusPoolt = haaletusPoolt;
		this.haaletusVastu = haaletusVastu;
		this.eriarvamused = eriarvamused;
		this.pkpNr = pkpNr;
		this.decisionTestItem = decisionTestItem;
		this.decisionTestItemStory = decisionTestItemStory;
		this.decisionNr = decisionNr;
		this.ukHelper = ukHelper;
		this.arCommiprotVotes = arCommiprotVotes;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_ADD_APPL_ID", nullable = false)
	public ArDocAddAppl getArDocAddAppl() {
		return this.arDocAddAppl;
	}

	public void setArDocAddAppl(ArDocAddAppl arDocAddAppl) {
		this.arDocAddAppl = arDocAddAppl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REG_NR")
	public ArCommeeting getArCommeeting() {
		return this.arCommeeting;
	}

	public void setArCommeeting(ArCommeeting arCommeeting) {
		this.arCommeeting = arCommeeting;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "PRO_TIME", nullable = false, length = 23)
	public Date getProTime() {
		return this.proTime;
	}

	public void setProTime(Date proTime) {
		this.proTime = proTime;
	}

	@Column(name = "DECISION_ANAL", nullable = false)
	public short getDecisionAnal() {
		return this.decisionAnal;
	}

	public void setDecisionAnal(short decisionAnal) {
		this.decisionAnal = decisionAnal;
	}

	@Column(name = "DECISION_STORY")
	public String getDecisionStory() {
		return this.decisionStory;
	}

	public void setDecisionStory(String decisionStory) {
		this.decisionStory = decisionStory;
	}

	@Column(name = "DECISION_ITEM", nullable = false)
	public short getDecisionItem() {
		return this.decisionItem;
	}

	public void setDecisionItem(short decisionItem) {
		this.decisionItem = decisionItem;
	}

	@Column(name = "DECISION_ITEM_STORY")
	public String getDecisionItemStory() {
		return this.decisionItemStory;
	}

	public void setDecisionItemStory(String decisionItemStory) {
		this.decisionItemStory = decisionItemStory;
	}

	@Column(name = "REG_BOOK_NR", length = 50)
	public String getRegBookNr() {
		return this.regBookNr;
	}

	public void setRegBookNr(String regBookNr) {
		this.regBookNr = regBookNr;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "VALIS_OSALEJA")
	public String getValisOsaleja() {
		return this.valisOsaleja;
	}

	public void setValisOsaleja(String valisOsaleja) {
		this.valisOsaleja = valisOsaleja;
	}

	@Column(name = "SQNAVQTUD")
	public String getSqnavqtud() {
		return this.sqnavqtud;
	}

	public void setSqnavqtud(String sqnavqtud) {
		this.sqnavqtud = sqnavqtud;
	}

	@Column(name = "HAALETUS_POOLT")
	public Integer getHaaletusPoolt() {
		return this.haaletusPoolt;
	}

	public void setHaaletusPoolt(Integer haaletusPoolt) {
		this.haaletusPoolt = haaletusPoolt;
	}

	@Column(name = "HAALETUS_VASTU")
	public Integer getHaaletusVastu() {
		return this.haaletusVastu;
	}

	public void setHaaletusVastu(Integer haaletusVastu) {
		this.haaletusVastu = haaletusVastu;
	}

	@Column(name = "ERIARVAMUSED")
	public String getEriarvamused() {
		return this.eriarvamused;
	}

	public void setEriarvamused(String eriarvamused) {
		this.eriarvamused = eriarvamused;
	}

	@Column(name = "PKP_NR")
	public Integer getPkpNr() {
		return this.pkpNr;
	}

	public void setPkpNr(Integer pkpNr) {
		this.pkpNr = pkpNr;
	}

	@Column(name = "DECISION_TEST_ITEM")
	public Short getDecisionTestItem() {
		return this.decisionTestItem;
	}

	public void setDecisionTestItem(Short decisionTestItem) {
		this.decisionTestItem = decisionTestItem;
	}

	@Column(name = "DECISION_TEST_ITEM_STORY")
	public String getDecisionTestItemStory() {
		return this.decisionTestItemStory;
	}

	public void setDecisionTestItemStory(String decisionTestItemStory) {
		this.decisionTestItemStory = decisionTestItemStory;
	}

	@Column(name = "DECISION_NR", length = 64)
	public String getDecisionNr() {
		return this.decisionNr;
	}

	public void setDecisionNr(String decisionNr) {
		this.decisionNr = decisionNr;
	}

	@Column(name = "UK_HELPER", nullable = false)
	public int getUkHelper() {
		return this.ukHelper;
	}

	public void setUkHelper(int ukHelper) {
		this.ukHelper = ukHelper;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arDocAddCommiprot")
	public Set<ArCommiprotVote> getArCommiprotVotes() {
		return this.arCommiprotVotes;
	}

	public void setArCommiprotVotes(Set<ArCommiprotVote> arCommiprotVotes) {
		this.arCommiprotVotes = arCommiprotVotes;
	}

}
