package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArDocAddAppl generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_APPL", schema = "dbo", catalog = "alkotest", uniqueConstraints = {
		@UniqueConstraint(columnNames = "DOC_NR"),
		@UniqueConstraint(columnNames = "ITEM_ID") })
public class ArDocAddAppl implements java.io.Serializable {

	private int id;

	private ArActor arActorByAppActorId;

	private ArItem arItem;

	private ArActor arActorByManActorId;

	private Date recTime;

	private int docNr;

	private Date insTime;

	private Date updTime;

	private Date arrTime;

	private int flags;

	private List<ArVeDocAddCommiprot> arDocAddCommiprots = new ArrayList<ArVeDocAddCommiprot>(
			0);

	public ArDocAddAppl() {
	}

	public ArDocAddAppl(int id, ArActor arActorByAppActorId, ArItem arItem,
			ArActor arActorByManActorId, Date recTime, int docNr, Date insTime,
			Date updTime, Date arrTime, int flags) {
		this.id = id;
		this.arActorByAppActorId = arActorByAppActorId;
		this.arItem = arItem;
		this.arActorByManActorId = arActorByManActorId;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.arrTime = arrTime;
		this.flags = flags;
	}

	public ArDocAddAppl(int id, ArActor arActorByAppActorId, ArItem arItem,
			ArActor arActorByManActorId, Date recTime, int docNr, Date insTime,
			Date updTime, Date arrTime, int flags,
			List<ArVeDocAddCommiprot> arDocAddCommiprots) {
		this.id = id;
		this.arActorByAppActorId = arActorByAppActorId;
		this.arItem = arItem;
		this.arActorByManActorId = arActorByManActorId;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.arrTime = arrTime;
		this.flags = flags;
		this.arDocAddCommiprots = arDocAddCommiprots;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "APP_ACTOR_ID", nullable = false)
	public ArActor getArActorByAppActorId() {
		return this.arActorByAppActorId;
	}

	public void setArActorByAppActorId(ArActor arActorByAppActorId) {
		this.arActorByAppActorId = arActorByAppActorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", unique = true, nullable = false)
	public ArItem getArItem() {
		return this.arItem;
	}

	public void setArItem(ArItem arItem) {
		this.arItem = arItem;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MAN_ACTOR_ID", nullable = false)
	public ArActor getArActorByManActorId() {
		return this.arActorByManActorId;
	}

	public void setArActorByManActorId(ArActor arActorByManActorId) {
		this.arActorByManActorId = arActorByManActorId;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", unique = true, nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "ARR_TIME", nullable = false, length = 23)
	public Date getArrTime() {
		return this.arrTime;
	}

	public void setArrTime(Date arrTime) {
		this.arrTime = arrTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "arDocAddAppl")
	public List<ArVeDocAddCommiprot> getArDocAddCommiprots() {
		return this.arDocAddCommiprots;
	}

	public void setArDocAddCommiprots(List<ArVeDocAddCommiprot> arDocAddCommiprots) {
		this.arDocAddCommiprots = arDocAddCommiprots;
	}

}
