package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArDocAddActperm generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_ACTPERM", schema = "dbo", catalog = "alkotest")
public class ArDocAddActperm implements java.io.Serializable {

	private int id;

	private ArActpermType arActpermType;

	private ArActorAddCont arActorAddCont;

	private ArAaRel arAaRel;

	private ArActor arActor;

	private Date recTime;

	private int docNr;

	private Date insTime;

	private Date updTime;

	private String regNr;

	private String specialRequ;

	private Date endTime;

	private Date susTime;

	private Date desTime;

	private int flags;

	private String desReference;

	private Date begTime;

	private String aaRelDescr;

	public ArDocAddActperm() {
	}

	public ArDocAddActperm(int id, ArActpermType arActpermType,
			ArAaRel arAaRel, ArActor arActor, Date recTime, int docNr,
			Date insTime, Date updTime, String regNr, Date endTime, int flags) {
		this.id = id;
		this.arActpermType = arActpermType;
		this.arAaRel = arAaRel;
		this.arActor = arActor;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.regNr = regNr;
		this.endTime = endTime;
		this.flags = flags;
	}

	public ArDocAddActperm(int id, ArActpermType arActpermType,
			ArActorAddCont arActorAddCont, ArAaRel arAaRel, ArActor arActor,
			Date recTime, int docNr, Date insTime, Date updTime, String regNr,
			String specialRequ, Date endTime, Date susTime, Date desTime,
			int flags, String desReference, Date begTime, String aaRelDescr) {
		this.id = id;
		this.arActpermType = arActpermType;
		this.arActorAddCont = arActorAddCont;
		this.arAaRel = arAaRel;
		this.arActor = arActor;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.regNr = regNr;
		this.specialRequ = specialRequ;
		this.endTime = endTime;
		this.susTime = susTime;
		this.desTime = desTime;
		this.flags = flags;
		this.desReference = desReference;
		this.begTime = begTime;
		this.aaRelDescr = aaRelDescr;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTPERM_TYPE_ID", nullable = false)
	public ArActpermType getArActpermType() {
		return this.arActpermType;
	}

	public void setArActpermType(ArActpermType arActpermType) {
		this.arActpermType = arActpermType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEL_ACTOR_ID")
	public ArActorAddCont getArActorAddCont() {
		return this.arActorAddCont;
	}

	public void setArActorAddCont(ArActorAddCont arActorAddCont) {
		this.arActorAddCont = arActorAddCont;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( { @JoinColumn(name = "DST_ACTOR_ID"),
			@JoinColumn(name = "RES_ACTOR_ID"),
			@JoinColumn(name = "REL_TYPE") })
	public ArAaRel getArAaRel() {
		return this.arAaRel;
	}

	public void setArAaRel(ArAaRel arAaRel) {
		this.arAaRel = arAaRel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ISS_ACTOR_ID", nullable = false)
	public ArActor getArActor() {
		return this.arActor;
	}

	public void setArActor(ArActor arActor) {
		this.arActor = arActor;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "REG_NR", nullable = false, length = 50)
	public String getRegNr() {
		return this.regNr;
	}

	public void setRegNr(String regNr) {
		this.regNr = regNr;
	}

	@Column(name = "SPECIAL_REQU")
	public String getSpecialRequ() {
		return this.specialRequ;
	}

	public void setSpecialRequ(String specialRequ) {
		this.specialRequ = specialRequ;
	}

	@Column(name = "END_TIME", nullable = false, length = 23)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "SUS_TIME", length = 23)
	public Date getSusTime() {
		return this.susTime;
	}

	public void setSusTime(Date susTime) {
		this.susTime = susTime;
	}

	@Column(name = "DES_TIME", length = 23)
	public Date getDesTime() {
		return this.desTime;
	}

	public void setDesTime(Date desTime) {
		this.desTime = desTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "DES_REFERENCE")
	public String getDesReference() {
		return this.desReference;
	}

	public void setDesReference(String desReference) {
		this.desReference = desReference;
	}

	@Column(name = "BEG_TIME", length = 23)
	public Date getBegTime() {
		return this.begTime;
	}

	public void setBegTime(Date begTime) {
		this.begTime = begTime;
	}

	@Column(name = "AA_REL__DESCR", length = 50)
	public String getAaRelDescr() {
		return this.aaRelDescr;
	}

	public void setAaRelDescr(String aaRelDescr) {
		this.aaRelDescr = aaRelDescr;
	}

}
