package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArDocAddBlading generated by hbm2java
 */
@Entity
@Table(name = "AR_DOC_ADD_BLADING", schema = "dbo", catalog = "alkotest")
public class ArDocAddBlading implements java.io.Serializable {

	private int id;

	private ArActor arActor;

	private Date recTime;

	private int docNr;

	private Date insTime;

	private Date updTime;

	private String remarks;

	private int flags;

	private Set<ArIbRel> arIbRels = new HashSet<ArIbRel>(0);

	public ArDocAddBlading() {
	}

	public ArDocAddBlading(int id, ArActor arActor, Date recTime, int docNr,
			Date insTime, Date updTime, int flags) {
		this.id = id;
		this.arActor = arActor;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArDocAddBlading(int id, ArActor arActor, Date recTime, int docNr,
			Date insTime, Date updTime, String remarks, int flags,
			Set<ArIbRel> arIbRels) {
		this.id = id;
		this.arActor = arActor;
		this.recTime = recTime;
		this.docNr = docNr;
		this.insTime = insTime;
		this.updTime = updTime;
		this.remarks = remarks;
		this.flags = flags;
		this.arIbRels = arIbRels;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DST_ACTOR_ID", nullable = false)
	public ArActor getArActor() {
		return this.arActor;
	}

	public void setArActor(ArActor arActor) {
		this.arActor = arActor;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "DOC_NR", nullable = false)
	public int getDocNr() {
		return this.docNr;
	}

	public void setDocNr(int docNr) {
		this.docNr = docNr;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arDocAddBlading")
	public Set<ArIbRel> getArIbRels() {
		return this.arIbRels;
	}

	public void setArIbRels(Set<ArIbRel> arIbRels) {
		this.arIbRels = arIbRels;
	}

}
