package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArEkn generated by hbm2java
 */
@Entity
@Table(name = "AR_EKN", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = "CODE"))
public class ArEkn implements java.io.Serializable {

	private int id;

	private ArMeasure arMeasure;

	private String code;

	private short lvl;

	private String name;

	private Date insTime;

	private Date updTime;

	private int flags;

	private Set<ArItem> arItems = new HashSet<ArItem>(0);

	public ArEkn() {
	}

	public ArEkn(int id, ArMeasure arMeasure, short lvl, String name,
			Date insTime, Date updTime, int flags) {
		this.id = id;
		this.arMeasure = arMeasure;
		this.lvl = lvl;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArEkn(int id, ArMeasure arMeasure, String code, short lvl,
			String name, Date insTime, Date updTime, int flags,
			Set<ArItem> arItems) {
		this.id = id;
		this.arMeasure = arMeasure;
		this.code = code;
		this.lvl = lvl;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.arItems = arItems;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEASURE_ID", nullable = false)
	public ArMeasure getArMeasure() {
		return this.arMeasure;
	}

	public void setArMeasure(ArMeasure arMeasure) {
		this.arMeasure = arMeasure;
	}

	@Column(name = "CODE", unique = true, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LVL", nullable = false)
	public short getLvl() {
		return this.lvl;
	}

	public void setLvl(short lvl) {
		this.lvl = lvl;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arEkn")
	public Set<ArItem> getArItems() {
		return this.arItems;
	}

	public void setArItems(Set<ArItem> arItems) {
		this.arItems = arItems;
	}

}
