package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArIbRelId generated by hbm2java
 */
@Embeddable
public class ArIbRelId implements java.io.Serializable {

	private int itemId;

	private int docAddBladingId;

	private short type;

	public ArIbRelId() {
	}

	public ArIbRelId(int itemId, int docAddBladingId, short type) {
		this.itemId = itemId;
		this.docAddBladingId = docAddBladingId;
		this.type = type;
	}

	@Column(name = "ITEM_ID", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "DOC_ADD_BLADING_ID", nullable = false)
	public int getDocAddBladingId() {
		return this.docAddBladingId;
	}

	public void setDocAddBladingId(int docAddBladingId) {
		this.docAddBladingId = docAddBladingId;
	}

	@Column(name = "TYPE", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArIbRelId))
			return false;
		ArIbRelId castOther = (ArIbRelId) other;

		return (this.getItemId() == castOther.getItemId())
				&& (this.getDocAddBladingId() == castOther.getDocAddBladingId())
				&& (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemId();
		result = 37 * result + this.getDocAddBladingId();
		result = 37 * result + this.getType();
		return result;
	}

}
