package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArIbRel generated by hbm2java
 */
@Entity
@Table(name = "AR_IB_REL", schema = "dbo", catalog = "alkotest")
public class ArIbRel implements java.io.Serializable {

	private ArIbRelId id;

	private ArItem arItem;

	private ArDocAddBlading arDocAddBlading;

	private Date itemIdTime;

	private BigDecimal quantity;

	private Date insTime;

	private Date updTime;

	private int id_1;

	public ArIbRel() {
	}

	public ArIbRel(ArIbRelId id, ArItem arItem,
			ArDocAddBlading arDocAddBlading, Date itemIdTime,
			BigDecimal quantity, Date insTime, Date updTime, int id_1) {
		this.id = id;
		this.arItem = arItem;
		this.arDocAddBlading = arDocAddBlading;
		this.itemIdTime = itemIdTime;
		this.quantity = quantity;
		this.insTime = insTime;
		this.updTime = updTime;
		this.id_1 = id_1;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "itemId", column = @Column(name = "ITEM_ID", nullable = false)),
			@AttributeOverride(name = "docAddBladingId", column = @Column(name = "DOC_ADD_BLADING_ID", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "TYPE", nullable = false)) })
	public ArIbRelId getId() {
		return this.id;
	}

	public void setId(ArIbRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false, insertable = false, updatable = false)
	public ArItem getArItem() {
		return this.arItem;
	}

	public void setArItem(ArItem arItem) {
		this.arItem = arItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOC_ADD_BLADING_ID", nullable = false, insertable = false, updatable = false)
	public ArDocAddBlading getArDocAddBlading() {
		return this.arDocAddBlading;
	}

	public void setArDocAddBlading(ArDocAddBlading arDocAddBlading) {
		this.arDocAddBlading = arDocAddBlading;
	}

	@Column(name = "ITEM_ID_TIME", nullable = false, length = 23)
	public Date getItemIdTime() {
		return this.itemIdTime;
	}

	public void setItemIdTime(Date itemIdTime) {
		this.itemIdTime = itemIdTime;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 23, scale = 8)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

}
