package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArItRel generated by hbm2java
 */
@Entity
@Table(name = "AR_IT_REL", schema = "dbo", catalog = "alkotest")
public class ArItRel implements java.io.Serializable {

	private ArItRelId id;

	private ArTpr arTpr;

	private ArItem arItem;

	private Date insTime;

	private Date updTime;

	public ArItRel() {
	}

	public ArItRel(ArItRelId id, ArTpr arTpr, ArItem arItem, Date insTime,
			Date updTime) {
		this.id = id;
		this.arTpr = arTpr;
		this.arItem = arItem;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "itemId", column = @Column(name = "ITEM_ID", nullable = false)),
			@AttributeOverride(name = "tprId", column = @Column(name = "TPR_ID", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "TYPE", nullable = false)) })
	public ArItRelId getId() {
		return this.id;
	}

	public void setId(ArItRelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPR_ID", nullable = false, insertable = false, updatable = false)
	public ArTpr getArTpr() {
		return this.arTpr;
	}

	public void setArTpr(ArTpr arTpr) {
		this.arTpr = arTpr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false, insertable = false, updatable = false)
	public ArItem getArItem() {
		return this.arItem;
	}

	public void setArItem(ArItem arItem) {
		this.arItem = arItem;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
