package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArItemMov generated by hbm2java
 */
@Entity
@Table(name = "AR_ITEM_MOV", schema = "dbo", catalog = "alkotest")
public class ArItemMov implements java.io.Serializable {

	private int id;

	private ArItem arItem;

	private ArActor arActor;

	private ArActorAddCont arActorAddCont;

	private Date movTime;

	private BigDecimal quantity;

	private String marking;

	private Date insTime;

	private Date updTime;

	private int flags;

	public ArItemMov() {
	}

	public ArItemMov(int id, ArItem arItem, ArActor arActor,
			ArActorAddCont arActorAddCont, Date movTime, Date insTime,
			Date updTime, int flags) {
		this.id = id;
		this.arItem = arItem;
		this.arActor = arActor;
		this.arActorAddCont = arActorAddCont;
		this.movTime = movTime;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArItemMov(int id, ArItem arItem, ArActor arActor,
			ArActorAddCont arActorAddCont, Date movTime, BigDecimal quantity,
			String marking, Date insTime, Date updTime, int flags) {
		this.id = id;
		this.arItem = arItem;
		this.arActor = arActor;
		this.arActorAddCont = arActorAddCont;
		this.movTime = movTime;
		this.quantity = quantity;
		this.marking = marking;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_ID", nullable = false)
	public ArItem getArItem() {
		return this.arItem;
	}

	public void setArItem(ArItem arItem) {
		this.arItem = arItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SRC_ACTOR_ID", nullable = false)
	public ArActor getArActor() {
		return this.arActor;
	}

	public void setArActor(ArActor arActor) {
		this.arActor = arActor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DST_ACTOR_ID", nullable = false)
	public ArActorAddCont getArActorAddCont() {
		return this.arActorAddCont;
	}

	public void setArActorAddCont(ArActorAddCont arActorAddCont) {
		this.arActorAddCont = arActorAddCont;
	}

	@Column(name = "MOV_TIME", nullable = false, length = 23)
	public Date getMovTime() {
		return this.movTime;
	}

	public void setMovTime(Date movTime) {
		this.movTime = movTime;
	}

	@Column(name = "QUANTITY", precision = 23, scale = 8)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "MARKING", length = 128)
	public String getMarking() {
		return this.marking;
	}

	public void setMarking(String marking) {
		this.marking = marking;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
