package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArItRelId generated by hbm2java
 */
@Embeddable
public class ArItRelId implements java.io.Serializable {

	private int itemId;

	private int tprId;

	private short type;

	public ArItRelId() {
	}

	public ArItRelId(int itemId, int tprId, short type) {
		this.itemId = itemId;
		this.tprId = tprId;
		this.type = type;
	}

	@Column(name = "ITEM_ID", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "TPR_ID", nullable = false)
	public int getTprId() {
		return this.tprId;
	}

	public void setTprId(int tprId) {
		this.tprId = tprId;
	}

	@Column(name = "TYPE", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArItRelId))
			return false;
		ArItRelId castOther = (ArItRelId) other;

		return (this.getItemId() == castOther.getItemId())
				&& (this.getTprId() == castOther.getTprId())
				&& (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemId();
		result = 37 * result + this.getTprId();
		result = 37 * result + this.getType();
		return result;
	}

}
