package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArItem generated by hbm2java
 */
@Entity
@Table(name = "AR_ITEM", schema = "dbo", catalog = "alkotest")
public class ArItem implements java.io.Serializable {

	private int id;

	private ArLtype arLtype;

	private ArProducttype arProducttype;

	private ArCapacity arCapacity;

	private ArCountry arCountry;

	private ArEkn arEkn;

	private ArMaterial arMaterial;

	private String name;

	private BigDecimal etanContent;

	private BigDecimal volume;

	private Short BStocking;

	private String descrSmell;

	private String descrCap;

	private String descrMark;

	private String descrLabel;

	private String descrBox;

	private String descrBottle;

	private String remarks;

	private byte[] picture;

	private BigDecimal packageCapacity;

	private String stockRef;

	private BigDecimal quantity;

	private Date insTime;

	private Date updTime;

	private int flags;

	private String comment;

	private Date outTime;

	private String outRemarks;

	private Set<ArItemMov> arItemMovs = new HashSet<ArItemMov>(0);

	private Set<ArDocAddAppl> arDocAddAppls = new HashSet<ArDocAddAppl>(0);

	private Set<ArItRel> arItRels = new HashSet<ArItRel>(0);

	private Set<ArIbRel> arIbRels = new HashSet<ArIbRel>(0);

	private Set<ArDocAddStat> arDocAddStats = new HashSet<ArDocAddStat>(0);

	public ArItem() {
	}

	public ArItem(int id, String name, BigDecimal quantity, Date insTime,
			Date updTime, int flags) {
		this.id = id;
		this.name = name;
		this.quantity = quantity;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArItem(int id, ArLtype arLtype, ArProducttype arProducttype,
			ArCapacity arCapacity, ArCountry arCountry, ArEkn arEkn,
			ArMaterial arMaterial, String name, BigDecimal etanContent,
			BigDecimal volume, Short BStocking, String descrSmell,
			String descrCap, String descrMark, String descrLabel,
			String descrBox, String descrBottle, String remarks,
			byte[] picture, BigDecimal packageCapacity, String stockRef,
			BigDecimal quantity, Date insTime, Date updTime, int flags,
			String comment, Date outTime, String outRemarks,
			Set<ArItemMov> arItemMovs, Set<ArDocAddAppl> arDocAddAppls,
			Set<ArItRel> arItRels, Set<ArIbRel> arIbRels,
			Set<ArDocAddStat> arDocAddStats) {
		this.id = id;
		this.arLtype = arLtype;
		this.arProducttype = arProducttype;
		this.arCapacity = arCapacity;
		this.arCountry = arCountry;
		this.arEkn = arEkn;
		this.arMaterial = arMaterial;
		this.name = name;
		this.etanContent = etanContent;
		this.volume = volume;
		this.BStocking = BStocking;
		this.descrSmell = descrSmell;
		this.descrCap = descrCap;
		this.descrMark = descrMark;
		this.descrLabel = descrLabel;
		this.descrBox = descrBox;
		this.descrBottle = descrBottle;
		this.remarks = remarks;
		this.picture = picture;
		this.packageCapacity = packageCapacity;
		this.stockRef = stockRef;
		this.quantity = quantity;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.comment = comment;
		this.outTime = outTime;
		this.outRemarks = outRemarks;
		this.arItemMovs = arItemMovs;
		this.arDocAddAppls = arDocAddAppls;
		this.arItRels = arItRels;
		this.arIbRels = arIbRels;
		this.arDocAddStats = arDocAddStats;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LTYPE_ID")
	public ArLtype getArLtype() {
		return this.arLtype;
	}

	public void setArLtype(ArLtype arLtype) {
		this.arLtype = arLtype;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCTTYPE_ID")
	public ArProducttype getArProducttype() {
		return this.arProducttype;
	}

	public void setArProducttype(ArProducttype arProducttype) {
		this.arProducttype = arProducttype;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "B_CAPACITY")
	public ArCapacity getArCapacity() {
		return this.arCapacity;
	}

	public void setArCapacity(ArCapacity arCapacity) {
		this.arCapacity = arCapacity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SRC_COUNTRY_ID")
	public ArCountry getArCountry() {
		return this.arCountry;
	}

	public void setArCountry(ArCountry arCountry) {
		this.arCountry = arCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EKN_ID")
	public ArEkn getArEkn() {
		return this.arEkn;
	}

	public void setArEkn(ArEkn arEkn) {
		this.arEkn = arEkn;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "B_MATERIAL")
	public ArMaterial getArMaterial() {
		return this.arMaterial;
	}

	public void setArMaterial(ArMaterial arMaterial) {
		this.arMaterial = arMaterial;
	}

	@Column(name = "NAME", nullable = false, length = 170)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ETAN_CONTENT", precision = 23, scale = 8)
	public BigDecimal getEtanContent() {
		return this.etanContent;
	}

	public void setEtanContent(BigDecimal etanContent) {
		this.etanContent = etanContent;
	}

	@Column(name = "VOLUME", precision = 23, scale = 8)
	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	@Column(name = "B_STOCKING")
	public Short getBStocking() {
		return this.BStocking;
	}

	public void setBStocking(Short BStocking) {
		this.BStocking = BStocking;
	}

	@Column(name = "DESCR_SMELL")
	public String getDescrSmell() {
		return this.descrSmell;
	}

	public void setDescrSmell(String descrSmell) {
		this.descrSmell = descrSmell;
	}

	@Column(name = "DESCR_CAP")
	public String getDescrCap() {
		return this.descrCap;
	}

	public void setDescrCap(String descrCap) {
		this.descrCap = descrCap;
	}

	@Column(name = "DESCR_MARK")
	public String getDescrMark() {
		return this.descrMark;
	}

	public void setDescrMark(String descrMark) {
		this.descrMark = descrMark;
	}

	@Column(name = "DESCR_LABEL")
	public String getDescrLabel() {
		return this.descrLabel;
	}

	public void setDescrLabel(String descrLabel) {
		this.descrLabel = descrLabel;
	}

	@Column(name = "DESCR_BOX")
	public String getDescrBox() {
		return this.descrBox;
	}

	public void setDescrBox(String descrBox) {
		this.descrBox = descrBox;
	}

	@Column(name = "DESCR_BOTTLE")
	public String getDescrBottle() {
		return this.descrBottle;
	}

	public void setDescrBottle(String descrBottle) {
		this.descrBottle = descrBottle;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "PICTURE")
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@Column(name = "PACKAGE_CAPACITY", precision = 23, scale = 8)
	public BigDecimal getPackageCapacity() {
		return this.packageCapacity;
	}

	public void setPackageCapacity(BigDecimal packageCapacity) {
		this.packageCapacity = packageCapacity;
	}

	@Column(name = "STOCK_REF", length = 100)
	public String getStockRef() {
		return this.stockRef;
	}

	public void setStockRef(String stockRef) {
		this.stockRef = stockRef;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 23, scale = 8)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "COMMENT")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "OUT_TIME", length = 23)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	@Column(name = "OUT_REMARKS")
	public String getOutRemarks() {
		return this.outRemarks;
	}

	public void setOutRemarks(String outRemarks) {
		this.outRemarks = outRemarks;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arItem")
	public Set<ArItemMov> getArItemMovs() {
		return this.arItemMovs;
	}

	public void setArItemMovs(Set<ArItemMov> arItemMovs) {
		this.arItemMovs = arItemMovs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "arItem")
	public Set<ArDocAddAppl> getArDocAddAppls() {
		return this.arDocAddAppls;
	}

	public void setArDocAddAppls(Set<ArDocAddAppl> arDocAddAppls) {
		this.arDocAddAppls = arDocAddAppls;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arItem")
	public Set<ArItRel> getArItRels() {
		return this.arItRels;
	}

	public void setArItRels(Set<ArItRel> arItRels) {
		this.arItRels = arItRels;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arItem")
	public Set<ArIbRel> getArIbRels() {
		return this.arIbRels;
	}

	public void setArIbRels(Set<ArIbRel> arIbRels) {
		this.arIbRels = arIbRels;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arItem")
	public Set<ArDocAddStat> getArDocAddStats() {
		return this.arDocAddStats;
	}

	public void setArDocAddStats(Set<ArDocAddStat> arDocAddStats) {
		this.arDocAddStats = arDocAddStats;
	}

}
