package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArJournalParams generated by hbm2java
 */
@Entity
@Table(name = "AR_JOURNAL_PARAMS", schema = "dbo", catalog = "alkotest")
public class ArJournalParams implements java.io.Serializable {

	private ArJournalParamsId id;

	private ArJournal arJournal;

	private String value;

	private int id_1;

	public ArJournalParams() {
	}

	public ArJournalParams(ArJournalParamsId id, ArJournal arJournal, int id_1) {
		this.id = id;
		this.arJournal = arJournal;
		this.id_1 = id_1;
	}

	public ArJournalParams(ArJournalParamsId id, ArJournal arJournal,
			String value, int id_1) {
		this.id = id;
		this.arJournal = arJournal;
		this.value = value;
		this.id_1 = id_1;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "journalId", column = @Column(name = "JOURNAL_ID", nullable = false)),
			@AttributeOverride(name = "param", column = @Column(name = "PARAM", nullable = false, length = 128)) })
	public ArJournalParamsId getId() {
		return this.id;
	}

	public void setId(ArJournalParamsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOURNAL_ID", nullable = false, insertable = false, updatable = false)
	public ArJournal getArJournal() {
		return this.arJournal;
	}

	public void setArJournal(ArJournal arJournal) {
		this.arJournal = arJournal;
	}

	@Column(name = "VALUE", length = 4000)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

}
