package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArJournalSeq generated by hbm2java
 */
@Entity
@Table(name = "AR_JOURNAL_SEQ", schema = "dbo", catalog = "alkotest")
public class ArJournalSeq implements java.io.Serializable {

	private int id;

	private Character c;

	public ArJournalSeq() {
	}

	public ArJournalSeq(int id) {
		this.id = id;
	}

	public ArJournalSeq(int id, Character c) {
		this.id = id;
		this.c = c;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "C", length = 1)
	public Character getC() {
		return this.c;
	}

	public void setC(Character c) {
		this.c = c;
	}

}
