package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArJournal generated by hbm2java
 */
@Entity
@Table(name = "AR_JOURNAL", schema = "dbo", catalog = "alkotest")
public class ArJournal implements java.io.Serializable {

	private int id;

	private Date recTime;

	private String objName;

	private String systemUserName;

	private int runtime;

	private Date insTime;

	private Date updTime;

	private Byte type;

	private byte[] colUpd;

	private Set<ArJournalParams> arJournalParamses = new HashSet<ArJournalParams>(
			0);

	public ArJournal() {
	}

	public ArJournal(int id, Date recTime, String objName,
			String systemUserName, int runtime, Date insTime, Date updTime) {
		this.id = id;
		this.recTime = recTime;
		this.objName = objName;
		this.systemUserName = systemUserName;
		this.runtime = runtime;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArJournal(int id, Date recTime, String objName,
			String systemUserName, int runtime, Date insTime, Date updTime,
			Byte type, byte[] colUpd, Set<ArJournalParams> arJournalParamses) {
		this.id = id;
		this.recTime = recTime;
		this.objName = objName;
		this.systemUserName = systemUserName;
		this.runtime = runtime;
		this.insTime = insTime;
		this.updTime = updTime;
		this.type = type;
		this.colUpd = colUpd;
		this.arJournalParamses = arJournalParamses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "OBJ_NAME", nullable = false, length = 128)
	public String getObjName() {
		return this.objName;
	}

	public void setObjName(String objName) {
		this.objName = objName;
	}

	@Column(name = "SYSTEM_USER_NAME", nullable = false, length = 128)
	public String getSystemUserName() {
		return this.systemUserName;
	}

	public void setSystemUserName(String systemUserName) {
		this.systemUserName = systemUserName;
	}

	@Column(name = "RUNTIME", nullable = false)
	public int getRuntime() {
		return this.runtime;
	}

	public void setRuntime(int runtime) {
		this.runtime = runtime;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "TYPE")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "COL_UPD")
	public byte[] getColUpd() {
		return this.colUpd;
	}

	public void setColUpd(byte[] colUpd) {
		this.colUpd = colUpd;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arJournal")
	public Set<ArJournalParams> getArJournalParamses() {
		return this.arJournalParamses;
	}

	public void setArJournalParamses(Set<ArJournalParams> arJournalParamses) {
		this.arJournalParamses = arJournalParamses;
	}

}
