package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArJournalParamsId generated by hbm2java
 */
@Embeddable
public class ArJournalParamsId implements java.io.Serializable {

	private int journalId;

	private String param;

	public ArJournalParamsId() {
	}

	public ArJournalParamsId(int journalId, String param) {
		this.journalId = journalId;
		this.param = param;
	}

	@Column(name = "JOURNAL_ID", nullable = false)
	public int getJournalId() {
		return this.journalId;
	}

	public void setJournalId(int journalId) {
		this.journalId = journalId;
	}

	@Column(name = "PARAM", nullable = false, length = 128)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArJournalParamsId))
			return false;
		ArJournalParamsId castOther = (ArJournalParamsId) other;

		return (this.getJournalId() == castOther.getJournalId())
				&& ((this.getParam() == castOther.getParam()) || (this
						.getParam() != null
						&& castOther.getParam() != null && this.getParam()
						.equals(castOther.getParam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJournalId();
		result = 37 * result
				+ (getParam() == null ? 0 : this.getParam().hashCode());
		return result;
	}

}
