package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArMeasure generated by hbm2java
 */
@Entity
@Table(name = "AR_MEASURE", schema = "dbo", catalog = "alkotest", uniqueConstraints = @UniqueConstraint(columnNames = "MEASURE"))
public class ArMeasure implements java.io.Serializable {

	private int id;

	private String measure;

	private String name;

	private Date insTime;

	private Date updTime;

	private int flags;

	private Set<ArEkn> arEkns = new HashSet<ArEkn>(0);

	public ArMeasure() {
	}

	public ArMeasure(int id, String measure, String name, Date insTime,
			Date updTime, int flags) {
		this.id = id;
		this.measure = measure;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArMeasure(int id, String measure, String name, Date insTime,
			Date updTime, int flags, Set<ArEkn> arEkns) {
		this.id = id;
		this.measure = measure;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.arEkns = arEkns;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MEASURE", unique = true, nullable = false, length = 20)
	public String getMeasure() {
		return this.measure;
	}

	public void setMeasure(String measure) {
		this.measure = measure;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arMeasure")
	public Set<ArEkn> getArEkns() {
		return this.arEkns;
	}

	public void setArEkns(Set<ArEkn> arEkns) {
		this.arEkns = arEkns;
	}

}
