package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArReports generated by hbm2java
 */
@Entity
@Table(name = "AR_REPORTS", schema = "dbo", catalog = "alkotest")
public class ArReports implements java.io.Serializable {

	private int reportId;

	private String viewSuffix;

	private String name;

	private String dataname;

	private byte[] imageReport;

	private Date insTime;

	private Date updTime;

	public ArReports() {
	}

	public ArReports(int reportId, String name, Date insTime, Date updTime) {
		this.reportId = reportId;
		this.name = name;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	public ArReports(int reportId, String viewSuffix, String name,
			String dataname, byte[] imageReport, Date insTime, Date updTime) {
		this.reportId = reportId;
		this.viewSuffix = viewSuffix;
		this.name = name;
		this.dataname = dataname;
		this.imageReport = imageReport;
		this.insTime = insTime;
		this.updTime = updTime;
	}

	@Id
	@Column(name = "REPORT_ID", unique = true, nullable = false)
	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	@Column(name = "VIEW_SUFFIX", length = 10)
	public String getViewSuffix() {
		return this.viewSuffix;
	}

	public void setViewSuffix(String viewSuffix) {
		this.viewSuffix = viewSuffix;
	}

	@Column(name = "NAME", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DATANAME", length = 30)
	public String getDataname() {
		return this.dataname;
	}

	public void setDataname(String dataname) {
		this.dataname = dataname;
	}

	@Column(name = "IMAGE_REPORT")
	public byte[] getImageReport() {
		return this.imageReport;
	}

	public void setImageReport(byte[] imageReport) {
		this.imageReport = imageReport;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

}
