package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArSessioncfg generated by hbm2java
 */
@Entity
@Table(name = "AR_SESSIONCFG", schema = "dbo", catalog = "alkotest")
public class ArSessioncfg implements java.io.Serializable {

	private int spid;

	private int flags;

	public ArSessioncfg() {
	}

	public ArSessioncfg(int spid, int flags) {
		this.spid = spid;
		this.flags = flags;
	}

	@Id
	@Column(name = "SPID", unique = true, nullable = false)
	public int getSpid() {
		return this.spid;
	}

	public void setSpid(int spid) {
		this.spid = spid;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
