package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArSession generated by hbm2java
 */
@Entity
@Table(name = "AR_SESSION", schema = "dbo", catalog = "alkotest")
public class ArSession implements java.io.Serializable {

	private int spid;

	private byte ignTriggers;

	private byte ignTtwrite;

	private byte ignParamwrite;

	private Integer ttLinkedToJournalId;

	private Date ttGetdate;

	private Integer ttObjectId;

	private Integer ttTrancount;

	private Integer ttNestlevel;

	private Date ttStarttime;

	private Integer journalId;

	private Integer RId1;

	private Integer RId2;

	private Integer RId3;

	private Integer RId4;

	private Integer RId5;

	private String RStr1;

	private String RStr2;

	private String RStr3;

	private String RStr4;

	private String RStr5;

	private BigDecimal RQ1;

	private BigDecimal RQ2;

	private BigDecimal RQ3;

	private BigDecimal RQ4;

	private BigDecimal RQ5;

	public ArSession() {
	}

	public ArSession(int spid, byte ignTriggers, byte ignTtwrite,
			byte ignParamwrite) {
		this.spid = spid;
		this.ignTriggers = ignTriggers;
		this.ignTtwrite = ignTtwrite;
		this.ignParamwrite = ignParamwrite;
	}

	public ArSession(int spid, byte ignTriggers, byte ignTtwrite,
			byte ignParamwrite, Integer ttLinkedToJournalId, Date ttGetdate,
			Integer ttObjectId, Integer ttTrancount, Integer ttNestlevel,
			Date ttStarttime, Integer journalId, Integer RId1, Integer RId2,
			Integer RId3, Integer RId4, Integer RId5, String RStr1,
			String RStr2, String RStr3, String RStr4, String RStr5,
			BigDecimal RQ1, BigDecimal RQ2, BigDecimal RQ3, BigDecimal RQ4,
			BigDecimal RQ5) {
		this.spid = spid;
		this.ignTriggers = ignTriggers;
		this.ignTtwrite = ignTtwrite;
		this.ignParamwrite = ignParamwrite;
		this.ttLinkedToJournalId = ttLinkedToJournalId;
		this.ttGetdate = ttGetdate;
		this.ttObjectId = ttObjectId;
		this.ttTrancount = ttTrancount;
		this.ttNestlevel = ttNestlevel;
		this.ttStarttime = ttStarttime;
		this.journalId = journalId;
		this.RId1 = RId1;
		this.RId2 = RId2;
		this.RId3 = RId3;
		this.RId4 = RId4;
		this.RId5 = RId5;
		this.RStr1 = RStr1;
		this.RStr2 = RStr2;
		this.RStr3 = RStr3;
		this.RStr4 = RStr4;
		this.RStr5 = RStr5;
		this.RQ1 = RQ1;
		this.RQ2 = RQ2;
		this.RQ3 = RQ3;
		this.RQ4 = RQ4;
		this.RQ5 = RQ5;
	}

	@Id
	@Column(name = "SPID", unique = true, nullable = false)
	public int getSpid() {
		return this.spid;
	}

	public void setSpid(int spid) {
		this.spid = spid;
	}

	@Column(name = "IGN_TRIGGERS", nullable = false)
	public byte getIgnTriggers() {
		return this.ignTriggers;
	}

	public void setIgnTriggers(byte ignTriggers) {
		this.ignTriggers = ignTriggers;
	}

	@Column(name = "IGN_TTWRITE", nullable = false)
	public byte getIgnTtwrite() {
		return this.ignTtwrite;
	}

	public void setIgnTtwrite(byte ignTtwrite) {
		this.ignTtwrite = ignTtwrite;
	}

	@Column(name = "IGN_PARAMWRITE", nullable = false)
	public byte getIgnParamwrite() {
		return this.ignParamwrite;
	}

	public void setIgnParamwrite(byte ignParamwrite) {
		this.ignParamwrite = ignParamwrite;
	}

	@Column(name = "TT_LINKED_TO_JOURNAL_ID")
	public Integer getTtLinkedToJournalId() {
		return this.ttLinkedToJournalId;
	}

	public void setTtLinkedToJournalId(Integer ttLinkedToJournalId) {
		this.ttLinkedToJournalId = ttLinkedToJournalId;
	}

	@Column(name = "TT_GETDATE", length = 23)
	public Date getTtGetdate() {
		return this.ttGetdate;
	}

	public void setTtGetdate(Date ttGetdate) {
		this.ttGetdate = ttGetdate;
	}

	@Column(name = "TT_OBJECT_ID")
	public Integer getTtObjectId() {
		return this.ttObjectId;
	}

	public void setTtObjectId(Integer ttObjectId) {
		this.ttObjectId = ttObjectId;
	}

	@Column(name = "TT_TRANCOUNT")
	public Integer getTtTrancount() {
		return this.ttTrancount;
	}

	public void setTtTrancount(Integer ttTrancount) {
		this.ttTrancount = ttTrancount;
	}

	@Column(name = "TT_NESTLEVEL")
	public Integer getTtNestlevel() {
		return this.ttNestlevel;
	}

	public void setTtNestlevel(Integer ttNestlevel) {
		this.ttNestlevel = ttNestlevel;
	}

	@Column(name = "TT_STARTTIME", length = 23)
	public Date getTtStarttime() {
		return this.ttStarttime;
	}

	public void setTtStarttime(Date ttStarttime) {
		this.ttStarttime = ttStarttime;
	}

	@Column(name = "JOURNAL_ID")
	public Integer getJournalId() {
		return this.journalId;
	}

	public void setJournalId(Integer journalId) {
		this.journalId = journalId;
	}

	@Column(name = "R_ID1")
	public Integer getRId1() {
		return this.RId1;
	}

	public void setRId1(Integer RId1) {
		this.RId1 = RId1;
	}

	@Column(name = "R_ID2")
	public Integer getRId2() {
		return this.RId2;
	}

	public void setRId2(Integer RId2) {
		this.RId2 = RId2;
	}

	@Column(name = "R_ID3")
	public Integer getRId3() {
		return this.RId3;
	}

	public void setRId3(Integer RId3) {
		this.RId3 = RId3;
	}

	@Column(name = "R_ID4")
	public Integer getRId4() {
		return this.RId4;
	}

	public void setRId4(Integer RId4) {
		this.RId4 = RId4;
	}

	@Column(name = "R_ID5")
	public Integer getRId5() {
		return this.RId5;
	}

	public void setRId5(Integer RId5) {
		this.RId5 = RId5;
	}

	@Column(name = "R_STR1")
	public String getRStr1() {
		return this.RStr1;
	}

	public void setRStr1(String RStr1) {
		this.RStr1 = RStr1;
	}

	@Column(name = "R_STR2")
	public String getRStr2() {
		return this.RStr2;
	}

	public void setRStr2(String RStr2) {
		this.RStr2 = RStr2;
	}

	@Column(name = "R_STR3")
	public String getRStr3() {
		return this.RStr3;
	}

	public void setRStr3(String RStr3) {
		this.RStr3 = RStr3;
	}

	@Column(name = "R_STR4")
	public String getRStr4() {
		return this.RStr4;
	}

	public void setRStr4(String RStr4) {
		this.RStr4 = RStr4;
	}

	@Column(name = "R_STR5")
	public String getRStr5() {
		return this.RStr5;
	}

	public void setRStr5(String RStr5) {
		this.RStr5 = RStr5;
	}

	@Column(name = "R_Q1", precision = 23, scale = 8)
	public BigDecimal getRQ1() {
		return this.RQ1;
	}

	public void setRQ1(BigDecimal RQ1) {
		this.RQ1 = RQ1;
	}

	@Column(name = "R_Q2", precision = 23, scale = 8)
	public BigDecimal getRQ2() {
		return this.RQ2;
	}

	public void setRQ2(BigDecimal RQ2) {
		this.RQ2 = RQ2;
	}

	@Column(name = "R_Q3", precision = 23, scale = 8)
	public BigDecimal getRQ3() {
		return this.RQ3;
	}

	public void setRQ3(BigDecimal RQ3) {
		this.RQ3 = RQ3;
	}

	@Column(name = "R_Q4", precision = 23, scale = 8)
	public BigDecimal getRQ4() {
		return this.RQ4;
	}

	public void setRQ4(BigDecimal RQ4) {
		this.RQ4 = RQ4;
	}

	@Column(name = "R_Q5", precision = 23, scale = 8)
	public BigDecimal getRQ5() {
		return this.RQ5;
	}

	public void setRQ5(BigDecimal RQ5) {
		this.RQ5 = RQ5;
	}

}
