package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArSysSeqcntId generated by hbm2java
 */
@Embeddable
public class ArSysSeqcntId implements java.io.Serializable {

	private String dbTableName;

	private String cntFieldName;

	public ArSysSeqcntId() {
	}

	public ArSysSeqcntId(String dbTableName, String cntFieldName) {
		this.dbTableName = dbTableName;
		this.cntFieldName = cntFieldName;
	}

	@Column(name = "DB_TABLE_NAME", nullable = false, length = 30)
	public String getDbTableName() {
		return this.dbTableName;
	}

	public void setDbTableName(String dbTableName) {
		this.dbTableName = dbTableName;
	}

	@Column(name = "CNT_FIELD_NAME", nullable = false, length = 30)
	public String getCntFieldName() {
		return this.cntFieldName;
	}

	public void setCntFieldName(String cntFieldName) {
		this.cntFieldName = cntFieldName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArSysSeqcntId))
			return false;
		ArSysSeqcntId castOther = (ArSysSeqcntId) other;

		return ((this.getDbTableName() == castOther.getDbTableName()) || (this
				.getDbTableName() != null
				&& castOther.getDbTableName() != null && this.getDbTableName()
				.equals(castOther.getDbTableName())))
				&& ((this.getCntFieldName() == castOther.getCntFieldName()) || (this
						.getCntFieldName() != null
						&& castOther.getCntFieldName() != null && this
						.getCntFieldName().equals(castOther.getCntFieldName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDbTableName() == null ? 0 : this.getDbTableName()
						.hashCode());
		result = 37
				* result
				+ (getCntFieldName() == null ? 0 : this.getCntFieldName()
						.hashCode());
		return result;
	}

}
