package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArSysSeqcnt generated by hbm2java
 */
@Entity
@Table(name = "AR_SYS_SEQCNT", schema = "dbo", catalog = "alkotest")
public class ArSysSeqcnt implements java.io.Serializable {

	private ArSysSeqcntId id;

	private int cnt;

	public ArSysSeqcnt() {
	}

	public ArSysSeqcnt(ArSysSeqcntId id, int cnt) {
		this.id = id;
		this.cnt = cnt;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "dbTableName", column = @Column(name = "DB_TABLE_NAME", nullable = false, length = 30)),
			@AttributeOverride(name = "cntFieldName", column = @Column(name = "CNT_FIELD_NAME", nullable = false, length = 30)) })
	public ArSysSeqcntId getId() {
		return this.id;
	}

	public void setId(ArSysSeqcntId id) {
		this.id = id;
	}

	@Column(name = "CNT", nullable = false)
	public int getCnt() {
		return this.cnt;
	}

	public void setCnt(int cnt) {
		this.cnt = cnt;
	}

}
