package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArTpr generated by hbm2java
 */
@Entity
@Table(name = "AR_TPR", schema = "dbo", catalog = "alkotest")
public class ArTpr implements java.io.Serializable {

	private int id;

	private String strtext;

	private byte[] picture;

	private Date insTime;

	private Date updTime;

	private int flags;

	private Set<ArItRel> arItRels = new HashSet<ArItRel>(0);

	public ArTpr() {
	}

	public ArTpr(int id, Date insTime, Date updTime, int flags) {
		this.id = id;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
	}

	public ArTpr(int id, String strtext, byte[] picture, Date insTime,
			Date updTime, int flags, Set<ArItRel> arItRels) {
		this.id = id;
		this.strtext = strtext;
		this.picture = picture;
		this.insTime = insTime;
		this.updTime = updTime;
		this.flags = flags;
		this.arItRels = arItRels;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "STRTEXT")
	public String getStrtext() {
		return this.strtext;
	}

	public void setStrtext(String strtext) {
		this.strtext = strtext;
	}

	@Column(name = "PICTURE")
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "arTpr")
	public Set<ArItRel> getArItRels() {
		return this.arItRels;
	}

	public void setArItRels(Set<ArItRel> arItRels) {
		this.arItRels = arItRels;
	}

}
