package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArVer generated by hbm2java
 */
@Entity
@Table(name = "AR_VER", schema = "dbo", catalog = "alkotest")
public class ArVer implements java.io.Serializable {

	private int dbVer;

	private Date dbUpdTime;

	private String clientVer;

	private int id;

	private Date insTime;

	private Integer viewVer;

	public ArVer() {
	}

	public ArVer(int dbVer, Date dbUpdTime, int id) {
		this.dbVer = dbVer;
		this.dbUpdTime = dbUpdTime;
		this.id = id;
	}

	public ArVer(int dbVer, Date dbUpdTime, String clientVer, int id,
			Date insTime, Integer viewVer) {
		this.dbVer = dbVer;
		this.dbUpdTime = dbUpdTime;
		this.clientVer = clientVer;
		this.id = id;
		this.insTime = insTime;
		this.viewVer = viewVer;
	}

	@Id
	@Column(name = "DB_VER", unique = true, nullable = false)
	public int getDbVer() {
		return this.dbVer;
	}

	public void setDbVer(int dbVer) {
		this.dbVer = dbVer;
	}

	@Column(name = "DB_UPD_TIME", nullable = false, length = 23)
	public Date getDbUpdTime() {
		return this.dbUpdTime;
	}

	public void setDbUpdTime(Date dbUpdTime) {
		this.dbUpdTime = dbUpdTime;
	}

	@Column(name = "CLIENT_VER", length = 20)
	public String getClientVer() {
		return this.clientVer;
	}

	public void setClientVer(String clientVer) {
		this.clientVer = clientVer;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "INS_TIME", length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "VIEW_VER")
	public Integer getViewVer() {
		return this.viewVer;
	}

	public void setViewVer(Integer viewVer) {
		this.viewVer = viewVer;
	}

}
