package ee.agri.alkor.util.convert.model.alkor1;

// Generated 23.02.2007 13:55:41 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArWwwDocActperm generated by hbm2java
 */
@Entity
@Table(name = "AR_WWW_DOC_ACTPERM", schema = "dbo", catalog = "alkotest")
public class ArWwwDocActperm implements java.io.Serializable {

	private int id;

	private ArActpermType arActpermType;

	private ArActor arActorByResActorId;

	private ArActor arActorByIssActorId;

	private ArActor arActorByDstActorId;

	private Date recTime;

	private Date insTime;

	private Date updTime;

	private String regNr;

	private String specialRequ;

	private Date endTime;

	private String dstName;

	private String dstForenames;

	private String dstCode;

	private String dstState;

	private String dstCity;

	private String dstAddress;

	private String dstZip;

	private String dstPhone;

	private String dstFax;

	private String dstEmail;

	private String dstCountryName;

	private String dstCountryIso2;

	private String dstCountryIso3;

	private String issName;

	private String issForenames;

	private String issCode;

	private String issState;

	private String issCity;

	private String issAddress;

	private String issZip;

	private String issPhone;

	private String issFax;

	private String issEmail;

	private String issCountryName;

	private String issCountryIso2;

	private String issCountryIso3;

	private String resName;

	private String resForenames;

	private String resCode;

	private String resState;

	private String resCity;

	private String resAddress;

	private String resZip;

	private String resPhone;

	private String resFax;

	private String resEmail;

	private String resCountryName;

	private String resCountryIso2;

	private String resCountryIso3;

	private int flags;

	private Integer arDocAddActpermId;

	private Date desTime;

	private Integer selActorId;

	private String selName;

	private String selForenames;

	private String selCode;

	private String selState;

	private String selCity;

	private String selAddress;

	private String selZip;

	private String selPhone;

	private String selFax;

	private String selEmail;

	private String selCountryName;

	private String selCountryIso2;

	private String selCountryIso3;

	private Date begTime;

	private String descr;

	public ArWwwDocActperm() {
	}

	public ArWwwDocActperm(int id, ArActpermType arActpermType, Date recTime,
			Date insTime, Date updTime, String regNr, int flags) {
		this.id = id;
		this.arActpermType = arActpermType;
		this.recTime = recTime;
		this.insTime = insTime;
		this.updTime = updTime;
		this.regNr = regNr;
		this.flags = flags;
	}

	public ArWwwDocActperm(int id, ArActpermType arActpermType,
			ArActor arActorByResActorId, ArActor arActorByIssActorId,
			ArActor arActorByDstActorId, Date recTime, Date insTime,
			Date updTime, String regNr, String specialRequ, Date endTime,
			String dstName, String dstForenames, String dstCode,
			String dstState, String dstCity, String dstAddress, String dstZip,
			String dstPhone, String dstFax, String dstEmail,
			String dstCountryName, String dstCountryIso2,
			String dstCountryIso3, String issName, String issForenames,
			String issCode, String issState, String issCity, String issAddress,
			String issZip, String issPhone, String issFax, String issEmail,
			String issCountryName, String issCountryIso2,
			String issCountryIso3, String resName, String resForenames,
			String resCode, String resState, String resCity, String resAddress,
			String resZip, String resPhone, String resFax, String resEmail,
			String resCountryName, String resCountryIso2,
			String resCountryIso3, int flags, Integer arDocAddActpermId,
			Date desTime, Integer selActorId, String selName,
			String selForenames, String selCode, String selState,
			String selCity, String selAddress, String selZip, String selPhone,
			String selFax, String selEmail, String selCountryName,
			String selCountryIso2, String selCountryIso3, Date begTime,
			String descr) {
		this.id = id;
		this.arActpermType = arActpermType;
		this.arActorByResActorId = arActorByResActorId;
		this.arActorByIssActorId = arActorByIssActorId;
		this.arActorByDstActorId = arActorByDstActorId;
		this.recTime = recTime;
		this.insTime = insTime;
		this.updTime = updTime;
		this.regNr = regNr;
		this.specialRequ = specialRequ;
		this.endTime = endTime;
		this.dstName = dstName;
		this.dstForenames = dstForenames;
		this.dstCode = dstCode;
		this.dstState = dstState;
		this.dstCity = dstCity;
		this.dstAddress = dstAddress;
		this.dstZip = dstZip;
		this.dstPhone = dstPhone;
		this.dstFax = dstFax;
		this.dstEmail = dstEmail;
		this.dstCountryName = dstCountryName;
		this.dstCountryIso2 = dstCountryIso2;
		this.dstCountryIso3 = dstCountryIso3;
		this.issName = issName;
		this.issForenames = issForenames;
		this.issCode = issCode;
		this.issState = issState;
		this.issCity = issCity;
		this.issAddress = issAddress;
		this.issZip = issZip;
		this.issPhone = issPhone;
		this.issFax = issFax;
		this.issEmail = issEmail;
		this.issCountryName = issCountryName;
		this.issCountryIso2 = issCountryIso2;
		this.issCountryIso3 = issCountryIso3;
		this.resName = resName;
		this.resForenames = resForenames;
		this.resCode = resCode;
		this.resState = resState;
		this.resCity = resCity;
		this.resAddress = resAddress;
		this.resZip = resZip;
		this.resPhone = resPhone;
		this.resFax = resFax;
		this.resEmail = resEmail;
		this.resCountryName = resCountryName;
		this.resCountryIso2 = resCountryIso2;
		this.resCountryIso3 = resCountryIso3;
		this.flags = flags;
		this.arDocAddActpermId = arDocAddActpermId;
		this.desTime = desTime;
		this.selActorId = selActorId;
		this.selName = selName;
		this.selForenames = selForenames;
		this.selCode = selCode;
		this.selState = selState;
		this.selCity = selCity;
		this.selAddress = selAddress;
		this.selZip = selZip;
		this.selPhone = selPhone;
		this.selFax = selFax;
		this.selEmail = selEmail;
		this.selCountryName = selCountryName;
		this.selCountryIso2 = selCountryIso2;
		this.selCountryIso3 = selCountryIso3;
		this.begTime = begTime;
		this.descr = descr;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTPERM_TYPE_ID", nullable = false)
	public ArActpermType getArActpermType() {
		return this.arActpermType;
	}

	public void setArActpermType(ArActpermType arActpermType) {
		this.arActpermType = arActpermType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RES_ACTOR_ID")
	public ArActor getArActorByResActorId() {
		return this.arActorByResActorId;
	}

	public void setArActorByResActorId(ArActor arActorByResActorId) {
		this.arActorByResActorId = arActorByResActorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ISS_ACTOR_ID")
	public ArActor getArActorByIssActorId() {
		return this.arActorByIssActorId;
	}

	public void setArActorByIssActorId(ArActor arActorByIssActorId) {
		this.arActorByIssActorId = arActorByIssActorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DST_ACTOR_ID")
	public ArActor getArActorByDstActorId() {
		return this.arActorByDstActorId;
	}

	public void setArActorByDstActorId(ArActor arActorByDstActorId) {
		this.arActorByDstActorId = arActorByDstActorId;
	}

	@Column(name = "REC_TIME", nullable = false, length = 23)
	public Date getRecTime() {
		return this.recTime;
	}

	public void setRecTime(Date recTime) {
		this.recTime = recTime;
	}

	@Column(name = "INS_TIME", nullable = false, length = 23)
	public Date getInsTime() {
		return this.insTime;
	}

	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	@Column(name = "UPD_TIME", nullable = false, length = 23)
	public Date getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Date updTime) {
		this.updTime = updTime;
	}

	@Column(name = "REG_NR", nullable = false, length = 50)
	public String getRegNr() {
		return this.regNr;
	}

	public void setRegNr(String regNr) {
		this.regNr = regNr;
	}

	@Column(name = "SPECIAL_REQU")
	public String getSpecialRequ() {
		return this.specialRequ;
	}

	public void setSpecialRequ(String specialRequ) {
		this.specialRequ = specialRequ;
	}

	@Column(name = "END_TIME", length = 23)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "DST_NAME", length = 170)
	public String getDstName() {
		return this.dstName;
	}

	public void setDstName(String dstName) {
		this.dstName = dstName;
	}

	@Column(name = "DST_FORENAMES", length = 100)
	public String getDstForenames() {
		return this.dstForenames;
	}

	public void setDstForenames(String dstForenames) {
		this.dstForenames = dstForenames;
	}

	@Column(name = "DST_CODE")
	public String getDstCode() {
		return this.dstCode;
	}

	public void setDstCode(String dstCode) {
		this.dstCode = dstCode;
	}

	@Column(name = "DST_STATE", length = 35)
	public String getDstState() {
		return this.dstState;
	}

	public void setDstState(String dstState) {
		this.dstState = dstState;
	}

	@Column(name = "DST_CITY", length = 35)
	public String getDstCity() {
		return this.dstCity;
	}

	public void setDstCity(String dstCity) {
		this.dstCity = dstCity;
	}

	@Column(name = "DST_ADDRESS", length = 35)
	public String getDstAddress() {
		return this.dstAddress;
	}

	public void setDstAddress(String dstAddress) {
		this.dstAddress = dstAddress;
	}

	@Column(name = "DST_ZIP", length = 10)
	public String getDstZip() {
		return this.dstZip;
	}

	public void setDstZip(String dstZip) {
		this.dstZip = dstZip;
	}

	@Column(name = "DST_PHONE", length = 100)
	public String getDstPhone() {
		return this.dstPhone;
	}

	public void setDstPhone(String dstPhone) {
		this.dstPhone = dstPhone;
	}

	@Column(name = "DST_FAX", length = 100)
	public String getDstFax() {
		return this.dstFax;
	}

	public void setDstFax(String dstFax) {
		this.dstFax = dstFax;
	}

	@Column(name = "DST_EMAIL", length = 100)
	public String getDstEmail() {
		return this.dstEmail;
	}

	public void setDstEmail(String dstEmail) {
		this.dstEmail = dstEmail;
	}

	@Column(name = "DST_COUNTRY_NAME")
	public String getDstCountryName() {
		return this.dstCountryName;
	}

	public void setDstCountryName(String dstCountryName) {
		this.dstCountryName = dstCountryName;
	}

	@Column(name = "DST_COUNTRY_ISO2", length = 2)
	public String getDstCountryIso2() {
		return this.dstCountryIso2;
	}

	public void setDstCountryIso2(String dstCountryIso2) {
		this.dstCountryIso2 = dstCountryIso2;
	}

	@Column(name = "DST_COUNTRY_ISO3", length = 3)
	public String getDstCountryIso3() {
		return this.dstCountryIso3;
	}

	public void setDstCountryIso3(String dstCountryIso3) {
		this.dstCountryIso3 = dstCountryIso3;
	}

	@Column(name = "ISS_NAME", length = 170)
	public String getIssName() {
		return this.issName;
	}

	public void setIssName(String issName) {
		this.issName = issName;
	}

	@Column(name = "ISS_FORENAMES", length = 100)
	public String getIssForenames() {
		return this.issForenames;
	}

	public void setIssForenames(String issForenames) {
		this.issForenames = issForenames;
	}

	@Column(name = "ISS_CODE")
	public String getIssCode() {
		return this.issCode;
	}

	public void setIssCode(String issCode) {
		this.issCode = issCode;
	}

	@Column(name = "ISS_STATE", length = 35)
	public String getIssState() {
		return this.issState;
	}

	public void setIssState(String issState) {
		this.issState = issState;
	}

	@Column(name = "ISS_CITY", length = 35)
	public String getIssCity() {
		return this.issCity;
	}

	public void setIssCity(String issCity) {
		this.issCity = issCity;
	}

	@Column(name = "ISS_ADDRESS", length = 35)
	public String getIssAddress() {
		return this.issAddress;
	}

	public void setIssAddress(String issAddress) {
		this.issAddress = issAddress;
	}

	@Column(name = "ISS_ZIP", length = 10)
	public String getIssZip() {
		return this.issZip;
	}

	public void setIssZip(String issZip) {
		this.issZip = issZip;
	}

	@Column(name = "ISS_PHONE", length = 100)
	public String getIssPhone() {
		return this.issPhone;
	}

	public void setIssPhone(String issPhone) {
		this.issPhone = issPhone;
	}

	@Column(name = "ISS_FAX", length = 100)
	public String getIssFax() {
		return this.issFax;
	}

	public void setIssFax(String issFax) {
		this.issFax = issFax;
	}

	@Column(name = "ISS_EMAIL", length = 100)
	public String getIssEmail() {
		return this.issEmail;
	}

	public void setIssEmail(String issEmail) {
		this.issEmail = issEmail;
	}

	@Column(name = "ISS_COUNTRY_NAME")
	public String getIssCountryName() {
		return this.issCountryName;
	}

	public void setIssCountryName(String issCountryName) {
		this.issCountryName = issCountryName;
	}

	@Column(name = "ISS_COUNTRY_ISO2", length = 2)
	public String getIssCountryIso2() {
		return this.issCountryIso2;
	}

	public void setIssCountryIso2(String issCountryIso2) {
		this.issCountryIso2 = issCountryIso2;
	}

	@Column(name = "ISS_COUNTRY_ISO3", length = 3)
	public String getIssCountryIso3() {
		return this.issCountryIso3;
	}

	public void setIssCountryIso3(String issCountryIso3) {
		this.issCountryIso3 = issCountryIso3;
	}

	@Column(name = "RES_NAME", length = 170)
	public String getResName() {
		return this.resName;
	}

	public void setResName(String resName) {
		this.resName = resName;
	}

	@Column(name = "RES_FORENAMES", length = 100)
	public String getResForenames() {
		return this.resForenames;
	}

	public void setResForenames(String resForenames) {
		this.resForenames = resForenames;
	}

	@Column(name = "RES_CODE")
	public String getResCode() {
		return this.resCode;
	}

	public void setResCode(String resCode) {
		this.resCode = resCode;
	}

	@Column(name = "RES_STATE", length = 35)
	public String getResState() {
		return this.resState;
	}

	public void setResState(String resState) {
		this.resState = resState;
	}

	@Column(name = "RES_CITY", length = 35)
	public String getResCity() {
		return this.resCity;
	}

	public void setResCity(String resCity) {
		this.resCity = resCity;
	}

	@Column(name = "RES_ADDRESS", length = 35)
	public String getResAddress() {
		return this.resAddress;
	}

	public void setResAddress(String resAddress) {
		this.resAddress = resAddress;
	}

	@Column(name = "RES_ZIP", length = 10)
	public String getResZip() {
		return this.resZip;
	}

	public void setResZip(String resZip) {
		this.resZip = resZip;
	}

	@Column(name = "RES_PHONE", length = 100)
	public String getResPhone() {
		return this.resPhone;
	}

	public void setResPhone(String resPhone) {
		this.resPhone = resPhone;
	}

	@Column(name = "RES_FAX", length = 100)
	public String getResFax() {
		return this.resFax;
	}

	public void setResFax(String resFax) {
		this.resFax = resFax;
	}

	@Column(name = "RES_EMAIL", length = 100)
	public String getResEmail() {
		return this.resEmail;
	}

	public void setResEmail(String resEmail) {
		this.resEmail = resEmail;
	}

	@Column(name = "RES_COUNTRY_NAME")
	public String getResCountryName() {
		return this.resCountryName;
	}

	public void setResCountryName(String resCountryName) {
		this.resCountryName = resCountryName;
	}

	@Column(name = "RES_COUNTRY_ISO2", length = 2)
	public String getResCountryIso2() {
		return this.resCountryIso2;
	}

	public void setResCountryIso2(String resCountryIso2) {
		this.resCountryIso2 = resCountryIso2;
	}

	@Column(name = "RES_COUNTRY_ISO3", length = 3)
	public String getResCountryIso3() {
		return this.resCountryIso3;
	}

	public void setResCountryIso3(String resCountryIso3) {
		this.resCountryIso3 = resCountryIso3;
	}

	@Column(name = "FLAGS", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "AR_DOC_ADD_ACTPERM_ID")
	public Integer getArDocAddActpermId() {
		return this.arDocAddActpermId;
	}

	public void setArDocAddActpermId(Integer arDocAddActpermId) {
		this.arDocAddActpermId = arDocAddActpermId;
	}

	@Column(name = "DES_TIME", length = 23)
	public Date getDesTime() {
		return this.desTime;
	}

	public void setDesTime(Date desTime) {
		this.desTime = desTime;
	}

	@Column(name = "SEL_ACTOR_ID")
	public Integer getSelActorId() {
		return this.selActorId;
	}

	public void setSelActorId(Integer selActorId) {
		this.selActorId = selActorId;
	}

	@Column(name = "SEL_NAME", length = 170)
	public String getSelName() {
		return this.selName;
	}

	public void setSelName(String selName) {
		this.selName = selName;
	}

	@Column(name = "SEL_FORENAMES", length = 100)
	public String getSelForenames() {
		return this.selForenames;
	}

	public void setSelForenames(String selForenames) {
		this.selForenames = selForenames;
	}

	@Column(name = "SEL_CODE")
	public String getSelCode() {
		return this.selCode;
	}

	public void setSelCode(String selCode) {
		this.selCode = selCode;
	}

	@Column(name = "SEL_STATE", length = 35)
	public String getSelState() {
		return this.selState;
	}

	public void setSelState(String selState) {
		this.selState = selState;
	}

	@Column(name = "SEL_CITY", length = 35)
	public String getSelCity() {
		return this.selCity;
	}

	public void setSelCity(String selCity) {
		this.selCity = selCity;
	}

	@Column(name = "SEL_ADDRESS", length = 35)
	public String getSelAddress() {
		return this.selAddress;
	}

	public void setSelAddress(String selAddress) {
		this.selAddress = selAddress;
	}

	@Column(name = "SEL_ZIP", length = 10)
	public String getSelZip() {
		return this.selZip;
	}

	public void setSelZip(String selZip) {
		this.selZip = selZip;
	}

	@Column(name = "SEL_PHONE", length = 100)
	public String getSelPhone() {
		return this.selPhone;
	}

	public void setSelPhone(String selPhone) {
		this.selPhone = selPhone;
	}

	@Column(name = "SEL_FAX", length = 100)
	public String getSelFax() {
		return this.selFax;
	}

	public void setSelFax(String selFax) {
		this.selFax = selFax;
	}

	@Column(name = "SEL_EMAIL", length = 100)
	public String getSelEmail() {
		return this.selEmail;
	}

	public void setSelEmail(String selEmail) {
		this.selEmail = selEmail;
	}

	@Column(name = "SEL_COUNTRY_NAME")
	public String getSelCountryName() {
		return this.selCountryName;
	}

	public void setSelCountryName(String selCountryName) {
		this.selCountryName = selCountryName;
	}

	@Column(name = "SEL_COUNTRY_ISO2", length = 2)
	public String getSelCountryIso2() {
		return this.selCountryIso2;
	}

	public void setSelCountryIso2(String selCountryIso2) {
		this.selCountryIso2 = selCountryIso2;
	}

	@Column(name = "SEL_COUNTRY_ISO3", length = 3)
	public String getSelCountryIso3() {
		return this.selCountryIso3;
	}

	public void setSelCountryIso3(String selCountryIso3) {
		this.selCountryIso3 = selCountryIso3;
	}

	@Column(name = "BEG_TIME", length = 23)
	public Date getBegTime() {
		return this.begTime;
	}

	public void setBegTime(Date begTime) {
		this.begTime = begTime;
	}

	@Column(name = "DESCR", length = 50)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
